import Foundation
import SwiftBebop
import Testing

@testable import BebopPlugin
@testable import bebopc_gen_swift

@Suite(.serialized)
struct SwiftGeneratorTests {

  // MARK: - Helpers

  private func generate(
    _ defs: DefinitionDescriptor...,
    package: String? = "test",
    options: GeneratorOptions = GeneratorOptions()
  ) throws -> String {
    let schema = SchemaDescriptor(
      path: "test.bop",
      package: package,
      definitions: defs
    )
    try NamingPolicy.registerSchemas([schema])
    GenerateService.definitionMap = buildDefinitionMap([schema])
    let generator = SwiftGenerator(options: options, compilerVersion: nil)
    return try generator.generate(schema: schema)
  }

  // MARK: - Header

  @Test func generatedHeader() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "X", fqn: "test.X",
        structDef: StructDef(fields: [], isMutable: false)
      )
    )
    #expect(code.hasPrefix("// Code generated by bebopc-gen-swift. DO NOT EDIT."))
    #expect(code.contains("import SwiftBebop"))
  }

  // MARK: - Enum

  @Test func enumBasic() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Color", fqn: "test.Color",
        enumDef: EnumDef(
          baseType: .uint32,
          members: [
            EnumMemberDescriptor(name: "Red", value: 0),
            EnumMemberDescriptor(name: "Green", value: 1),
            EnumMemberDescriptor(name: "Blue", value: 2),
          ], isFlags: false)
      ))
    #expect(code.contains("public struct Color: RawRepresentable"))
    #expect(code.contains("BebopRecord"))
    #expect(code.contains("public let rawValue: UInt32"))
    #expect(code.contains("static let red = Color(rawValue: 0)"))
    #expect(code.contains("static let green = Color(rawValue: 1)"))
    #expect(code.contains("static let blue = Color(rawValue: 2)"))
    #expect(code.contains("readUInt32"))
    #expect(code.contains("writeUInt32"))
  }

  @Test func enumFlags() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Perms", fqn: "test.Perms",
        enumDef: EnumDef(
          baseType: .byte,
          members: [
            EnumMemberDescriptor(name: "None", value: 0),
            EnumMemberDescriptor(name: "Read", value: 1),
            EnumMemberDescriptor(name: "Write", value: 2),
            EnumMemberDescriptor(name: "Execute", value: 4),
          ], isFlags: true)
      ))
    #expect(code.contains("public struct Perms: OptionSet"))
    #expect(code.contains("public let rawValue: UInt8"))
    // None (value 0) excluded from flags
    #expect(!code.contains("static let none"))
    #expect(code.contains("static let read = Perms(rawValue: 1)"))
    #expect(code.contains("static let write = Perms(rawValue: 2)"))
    #expect(code.contains("static let execute = Perms(rawValue: 4)"))
    // Flags get custom Codable
    #expect(code.contains("init(from decoder: Decoder)"))
    #expect(code.contains("singleValueContainer"))
  }

  @Test func enumEmpty() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Empty", fqn: "test.Empty",
        enumDef: EnumDef(baseType: .uint32, members: [], isFlags: false)
      ))
    #expect(code.contains("public struct Empty: RawRepresentable"))
  }

  @Test func enumDocComment() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Status", fqn: "test.Status",
        documentation: "HTTP status codes.",
        enumDef: EnumDef(
          baseType: .uint16,
          members: [
            EnumMemberDescriptor(name: "OK", value: 200)
          ], isFlags: false)
      ))
    #expect(code.contains("/// HTTP status codes."))
  }

  @Test func enumDeprecatedMember() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Level", fqn: "test.Level",
        enumDef: EnumDef(
          baseType: .uint32,
          members: [
            EnumMemberDescriptor(
              name: "Low", value: 0,
              decorators: [
                DecoratorUsage(
                  fqn: "deprecated",
                  args: [
                    DecoratorArg(
                      name: "", value: LiteralValue(kind: .string, stringValue: "use Medium"))
                  ])
              ]),
            EnumMemberDescriptor(name: "Medium", value: 1),
          ], isFlags: false)
      ))
    #expect(code.contains("@available(*, deprecated, message: \"use Medium\")"))
  }

  @Test func enumSignedBaseType() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Offset", fqn: "test.Offset",
        enumDef: EnumDef(
          baseType: .int32,
          members: [
            EnumMemberDescriptor(name: "Neg", value: 0xFFFF_FFFF),
            EnumMemberDescriptor(name: "Zero", value: 0),
            EnumMemberDescriptor(name: "Pos", value: 1),
          ], isFlags: false)
      ))
    #expect(code.contains("public let rawValue: Int32"))
    #expect(code.contains("rawValue: -1"))
    #expect(code.contains("rawValue: 0"))
    #expect(code.contains("rawValue: 1"))
  }

  @Test func enumEncodedSize() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Small", fqn: "test.Small",
        enumDef: EnumDef(
          baseType: .byte,
          members: [
            EnumMemberDescriptor(name: "A", value: 0)
          ], isFlags: false)
      ))
    // byte enum = 1 byte
    #expect(code.contains("encodedSize: Int"))
    #expect(code.contains("1"))
  }

  @Test func enumReflection() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .enum, name: "Color", fqn: "test.Color",
        enumDef: EnumDef(
          baseType: .uint32,
          members: [
            EnumMemberDescriptor(name: "Red", value: 0)
          ], isFlags: false)
      ))
    #expect(code.contains("bebopReflection"))
    #expect(code.contains("name: \"Color\""))
    #expect(code.contains("fqn: \"test.Color\""))
    #expect(code.contains("isFlags: false"))
  }

  // MARK: - Struct

  @Test func structScalarFields() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Point", fqn: "test.Point",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "x", type: TypeDescriptor(kind: .float32)),
            FieldDescriptor(name: "y", type: TypeDescriptor(kind: .float32)),
          ], isMutable: false)
      ))
    #expect(code.contains("public struct Point: BebopRecord"))
    #expect(code.contains("public let x: Float"))
    #expect(code.contains("public let y: Float"))
    // Fixed size: 4 + 4 = 8
    #expect(code.contains("encodedSize: Int"))
    #expect(code.contains("8"))
  }

  @Test func structMutable() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "MutPoint", fqn: "test.MutPoint",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "x", type: TypeDescriptor(kind: .float32))
          ], isMutable: true)
      ))
    #expect(code.contains("public var x: Float"))
  }

  @Test func structVariableSize() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Named", fqn: "test.Named",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "name", type: TypeDescriptor(kind: .string)),
            FieldDescriptor(name: "id", type: TypeDescriptor(kind: .uint32)),
          ], isMutable: false)
      ))
    #expect(code.contains("public let name: String"))
    #expect(code.contains("public let id: UInt32"))
    #expect(code.contains("var size = 0"))
    #expect(code.contains("size += (4 + name.utf8.count + 1)"))
    #expect(code.contains("size += 4"))
  }

  @Test func structEmpty() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Empty", fqn: "test.Empty",
        structDef: StructDef(fields: [], isMutable: false)
      ))
    #expect(code.contains("public struct Empty: BebopRecord"))
    // Empty struct: constant 0 encodedSize
    #expect(code.contains("0"))
  }

  @Test func structCodingKeys() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "User", fqn: "test.User",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "first_name", type: TypeDescriptor(kind: .string)),
            FieldDescriptor(name: "last_name", type: TypeDescriptor(kind: .string)),
          ], isMutable: false)
      ))
    #expect(code.contains("public let firstName: String"))
    #expect(code.contains("public let lastName: String"))
    #expect(code.contains("case firstName = \"first_name\""))
    #expect(code.contains("case lastName = \"last_name\""))
  }

  @Test func structArrayField() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "List", fqn: "test.List",
        structDef: StructDef(
          fields: [
            FieldDescriptor(
              name: "items",
              type: TypeDescriptor(
                kind: .array, arrayElement: TypeDescriptor(kind: .int32)
              ))
          ], isMutable: false)
      ))
    #expect(code.contains("public let items: [Int32]"))
    #expect(code.contains("readLengthPrefixedArray"))
    #expect(code.contains("writeLengthPrefixedArray"))
  }

  @Test func structMapField() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Dict", fqn: "test.Dict",
        structDef: StructDef(
          fields: [
            FieldDescriptor(
              name: "data",
              type: TypeDescriptor(
                kind: .map,
                mapKey: TypeDescriptor(kind: .string),
                mapValue: TypeDescriptor(kind: .uint32)
              ))
          ], isMutable: false)
      ))
    #expect(code.contains("public let data: [String: UInt32]"))
  }

  @Test func structDefinedTypeField() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Inner", fqn: "test.Inner",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "value", type: TypeDescriptor(kind: .int32))
          ], isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "Outer", fqn: "test.Outer",
        structDef: StructDef(
          fields: [
            FieldDescriptor(
              name: "inner", type: TypeDescriptor(kind: .defined, definedFqn: "test.Inner"))
          ], isMutable: false)
      )
    )
    #expect(code.contains("public let inner: Inner"))
    #expect(code.contains("try Inner.decode(from: &reader)"))
  }

  @Test func structFixedArrayField() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Matrix", fqn: "test.Matrix",
        structDef: StructDef(
          fields: [
            FieldDescriptor(
              name: "values",
              type: TypeDescriptor(
                kind: .fixedArray,
                fixedArrayElement: TypeDescriptor(kind: .float32),
                fixedArraySize: 16
              ))
          ], isMutable: false)
      ))
    #expect(code.contains("InlineArray<16, Float>"))
    #expect(code.contains("readInlineArray"))
  }

  @Test func structReflection() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Point", fqn: "test.Point",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "x", type: TypeDescriptor(kind: .float32))
          ], isMutable: false)
      ))
    #expect(code.contains("bebopReflection"))
    #expect(code.contains("name: \"Point\""))
    #expect(code.contains("fqn: \"test.Point\""))
    #expect(code.contains("kind: .struct"))
  }

  // MARK: - Message

  @Test func messageBasic() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Request", fqn: "test.Request",
        messageDef: MessageDef(fields: [
          FieldDescriptor(name: "url", type: TypeDescriptor(kind: .string), index: 1),
          FieldDescriptor(name: "timeout", type: TypeDescriptor(kind: .uint32), index: 2),
        ])
      ))
    #expect(code.contains("public final class Request: BebopRecord"))
    #expect(code.contains("@unchecked Sendable"))
    #expect(code.contains("public var url: String?"))
    #expect(code.contains("public var timeout: UInt32?"))
    #expect(code.contains("writer.writeTag(1)"))
    #expect(code.contains("writer.writeTag(2)"))
    #expect(code.contains("reserveMessageLength"))
    #expect(code.contains("fillMessageLength"))
  }

  @Test func messageEmpty() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Ping", fqn: "test.Ping",
        messageDef: MessageDef(fields: [])
      ))
    #expect(code.contains("public final class Ping: BebopRecord"))
    // Empty message: 4 bytes length + 1 byte end marker = 5
    #expect(code.contains("encodedSize: Int"))
    #expect(code.contains("5"))
  }

  @Test func messageDeprecatedField() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Msg", fqn: "test.Msg",
        messageDef: MessageDef(fields: [
          FieldDescriptor(
            name: "old_field", type: TypeDescriptor(kind: .string), index: 1,
            decorators: [DecoratorUsage(fqn: "deprecated")]),
          FieldDescriptor(name: "new_field", type: TypeDescriptor(kind: .string), index: 2),
        ])
      ))
    #expect(code.contains("@available(*, deprecated)"))
  }

  @Test func messageEquality() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Msg", fqn: "test.Msg",
        messageDef: MessageDef(fields: [
          FieldDescriptor(name: "a", type: TypeDescriptor(kind: .int32), index: 1),
          FieldDescriptor(name: "b", type: TypeDescriptor(kind: .int32), index: 2),
        ])
      ))
    #expect(code.contains("static func == (lhs: Msg, rhs: Msg) -> Bool"))
    #expect(code.contains("lhs.a == rhs.a && lhs.b == rhs.b"))
  }

  @Test func messageEmptyEquality() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Ping", fqn: "test.Ping",
        messageDef: MessageDef(fields: [])
      ))
    #expect(code.contains("return true"))
  }

  @Test func messageCodingKeys() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Msg", fqn: "test.Msg",
        messageDef: MessageDef(fields: [
          FieldDescriptor(name: "user_id", type: TypeDescriptor(kind: .uint32), index: 1)
        ])
      ))
    #expect(code.contains("case userId = \"user_id\""))
  }

  @Test func messageUnknownFieldSkip() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "Msg", fqn: "test.Msg",
        messageDef: MessageDef(fields: [
          FieldDescriptor(name: "x", type: TypeDescriptor(kind: .int32), index: 1)
        ])
      ))
    // Unknown tags skip to end
    #expect(code.contains("reader.skip(end - reader.position)"))
  }

  // MARK: - Union

  @Test func unionBasic() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Success", fqn: "test.Success",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "value", type: TypeDescriptor(kind: .string))
          ], isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "Error", fqn: "test.Error",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "code", type: TypeDescriptor(kind: .int32))
          ], isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .union, name: "Result", fqn: "test.Result",
        unionDef: UnionDef(branches: [
          UnionBranchDescriptor(discriminator: 1, typeRefFqn: "test.Success", name: "Success"),
          UnionBranchDescriptor(discriminator: 2, typeRefFqn: "test.Error", name: "Error"),
        ])
      )
    )
    #expect(code.contains("public enum Result: BebopRecord"))
    #expect(code.contains("case unknown(discriminator: UInt8, data: [UInt8])"))
    #expect(code.contains("case success(Success)"))
    #expect(code.contains("case error(Error)"))
    // Discriminator-based decode
    #expect(code.contains("case 1:"))
    #expect(code.contains("case 2:"))
  }

  @Test func unionCodable() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "A", fqn: "test.A",
        structDef: StructDef(fields: [], isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .union, name: "U", fqn: "test.U",
        unionDef: UnionDef(branches: [
          UnionBranchDescriptor(discriminator: 1, typeRefFqn: "test.A", name: "A")
        ])
      )
    )
    #expect(code.contains("CodingKeys: String, CodingKey"))
    #expect(code.contains("discriminator"))
    #expect(code.contains("init(from decoder: Decoder)"))
  }

  @Test func unionEncodedSize() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "A", fqn: "test.A",
        structDef: StructDef(fields: [], isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .union, name: "U", fqn: "test.U",
        unionDef: UnionDef(branches: [
          UnionBranchDescriptor(discriminator: 1, typeRefFqn: "test.A", name: "A")
        ])
      )
    )
    // 4 bytes length + 1 byte discriminator + inner.encodedSize
    #expect(code.contains("4 + 1 + _v.encodedSize"))
  }

  // MARK: - Const

  @Test func constString() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "APP_NAME", fqn: "test.APP_NAME",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .string),
          value: LiteralValue(kind: .string, stringValue: "MyApp")
        )
      ))
    #expect(code.contains("public let appName: String = \"MyApp\""))
  }

  @Test func constInt() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "MAX_SIZE", fqn: "test.MAX_SIZE",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .uint32),
          value: LiteralValue(kind: .int, intValue: 1024)
        )
      ))
    #expect(code.contains("public let maxSize: UInt32 = 1024"))
  }

  @Test func constBool() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "DEBUG", fqn: "test.DEBUG",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .bool),
          value: LiteralValue(kind: .bool, boolValue: true)
        )
      ))
    #expect(code.contains("public let debug: Bool = true"))
  }

  @Test func constFloat() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "PI", fqn: "test.PI",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .float64),
          value: LiteralValue(kind: .float, floatValue: 3.14159)
        )
      ))
    #expect(code.contains("public let pi: Double = 3.14159"))
  }

  @Test func constUUID() throws {
    let id = BebopUUID(uuidString: "12345678-1234-5678-1234-567812345678")!
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "TEST_ID", fqn: "test.TEST_ID",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .uuid),
          value: LiteralValue(kind: .uuid, uuidValue: id)
        )
      ))
    #expect(code.contains("public let testId: BebopUUID = BebopUUID(uuidString:"))
  }

  @Test func constStringEscaping() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "QUOTE", fqn: "test.QUOTE",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .string),
          value: LiteralValue(kind: .string, stringValue: "he said \"hello\"")
        )
      ))
    #expect(code.contains("he said \\\"hello\\\""))
  }

  // MARK: - Well-Known Types

  @Test func wellKnownAnySkipped() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Any", fqn: "bebop.Any",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "type_url", type: TypeDescriptor(kind: .string)),
            FieldDescriptor(
              name: "value",
              type: TypeDescriptor(
                kind: .array, arrayElement: TypeDescriptor(kind: .byte)
              )),
          ], isMutable: false)
      ),
      package: "bebop"
    )
    #expect(!code.contains("struct Any"))
    #expect(!code.contains("struct `Any`"))
  }

  @Test func wellKnownTypeURLPrefixSkipped() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .const, name: "TYPE_URL_PREFIX", fqn: "bebop.TYPE_URL_PREFIX",
        constDef: ConstDef(
          type: TypeDescriptor(kind: .string),
          value: LiteralValue(kind: .string, stringValue: "type.bebop.sh/")
        )
      ),
      package: "bebop"
    )
    #expect(!code.contains("typeUrlPrefix"))
    #expect(!code.contains("TYPE_URL_PREFIX"))
  }

  @Test func wellKnownFQNResolvesToBebopAny() throws {
    let schema = SchemaDescriptor(
      path: "test.bop",
      package: "test",
      definitions: [
        DefinitionDescriptor(
          kind: .struct, name: "Wrapper", fqn: "test.Wrapper",
          structDef: StructDef(
            fields: [
              FieldDescriptor(
                name: "payload",
                type: TypeDescriptor(
                  kind: .defined, definedFqn: "bebop.Any"
                ))
            ], isMutable: false)
        )
      ]
    )
    try NamingPolicy.registerSchemas([schema])
    #expect(NamingPolicy.fqnToTypeName("bebop.Any") == "BebopAny")
  }

  @Test func wellKnownFQNInGeneratedCode() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Wrapper", fqn: "test.Wrapper",
        structDef: StructDef(
          fields: [
            FieldDescriptor(
              name: "payload",
              type: TypeDescriptor(
                kind: .defined, definedFqn: "bebop.Any"
              ))
          ], isMutable: false)
      )
    )
    #expect(code.contains("public let payload: BebopAny"))
    #expect(code.contains("try BebopAny.decode(from: &reader)"))
  }

  @Test func nonWellKnownBebopPackageStillGenerated() throws {
    // Other bebop.* types (not in wellKnownFQNs) should still generate
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Custom", fqn: "bebop.Custom",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "id", type: TypeDescriptor(kind: .uint32))
          ], isMutable: false)
      ),
      package: "bebop"
    )
    #expect(code.contains("struct Custom: BebopRecord"))
  }

  // MARK: - Visibility

  @Test func internalVisibility() throws {
    var opts = GeneratorOptions()
    opts.visibility = "internal "
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Secret", fqn: "test.Secret",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "key", type: TypeDescriptor(kind: .string))
          ], isMutable: false)
      ),
      options: opts
    )
    #expect(code.contains("internal struct Secret: BebopRecord"))
    #expect(code.contains("internal let key: String"))
  }

  @Test func localVisibilityOverridesToInternal() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Local", fqn: "test.Local",
        visibility: .local,
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "val", type: TypeDescriptor(kind: .int32))
          ], isMutable: false)
      ))
    #expect(code.contains("internal struct Local: BebopRecord"))
  }

  // MARK: - NamingPolicy

  @Test func camelCaseSnakeCase() {
    #expect(NamingPolicy.fieldName("my_field") == "myField")
    #expect(NamingPolicy.fieldName("some_long_name") == "someLongName")
  }

  @Test func camelCaseFromPascal() {
    #expect(NamingPolicy.fieldName("MyField") == "myField")
    #expect(NamingPolicy.fieldName("URL") == "url")
  }

  @Test func camelCaseFromAllCaps() {
    #expect(NamingPolicy.fieldName("APP_NAME") == "appName")
    #expect(NamingPolicy.fieldName("MAX_SIZE") == "maxSize")
  }

  @Test func camelCaseAlreadyCamel() {
    #expect(NamingPolicy.fieldName("alreadyCamel") == "alreadyCamel")
  }

  @Test func keywordEscaping() {
    #expect(NamingPolicy.typeName("class") == "`class`")
    #expect(NamingPolicy.typeName("struct") == "`struct`")
    #expect(NamingPolicy.typeName("enum") == "`enum`")
    #expect(NamingPolicy.typeName("import") == "`import`")
    #expect(NamingPolicy.typeName("MyType") == "MyType")
  }

  @Test func fqnRegistration() throws {
    let schema = SchemaDescriptor(
      path: "test.bop",
      package: "test",
      definitions: [
        DefinitionDescriptor(
          kind: .struct, name: "Foo", fqn: "test.Foo",
          structDef: StructDef(fields: [], isMutable: false)),
        DefinitionDescriptor(
          kind: .struct, name: "Bar", fqn: "test.Bar",
          structDef: StructDef(fields: [], isMutable: false)),
      ]
    )
    try NamingPolicy.registerSchemas([schema])
    #expect(NamingPolicy.fqnToTypeName("test.Foo") == "Foo")
    #expect(NamingPolicy.fqnToTypeName("test.Bar") == "Bar")
  }

  @Test func wellKnownFQNSurvivesRegistration() throws {
    try NamingPolicy.registerSchemas([
      SchemaDescriptor(path: "test.bop", package: "test", definitions: [])
    ])
    #expect(NamingPolicy.fqnToTypeName("bebop.Any") == "BebopAny")
  }

  // MARK: - Service / Decorator (skipped kinds)

  @Test func serviceEmptySkipped() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .service, name: "MyService", fqn: "test.MyService",
        serviceDef: ServiceDef(methods: [])
      ))
    #expect(!code.contains("MyService"))
  }

  @Test func serviceSkippedWhenNone() throws {
    var opts = GeneratorOptions()
    opts.services = .none
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "GetUserRequest", fqn: "test.GetUserRequest",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "id", type: TypeDescriptor(kind: .uint32))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "User", fqn: "test.User",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "name", type: TypeDescriptor(kind: .string))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "UserService", fqn: "test.UserService",
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "GetUser",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.GetUserRequest"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.User"),
            methodType: .unary, id: 0xAABB_CCDD)
        ])
      ),
      options: opts
    )
    #expect(!code.contains("BebopServiceDefinition"))
    #expect(!code.contains("UserServiceClient"))
  }

  @Test func decoratorSkipped() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .decorator, name: "deprecated", fqn: "deprecated",
        decoratorDef: DecoratorDef()
      ),
      package: nil
    )
    #expect(!code.contains("struct deprecated"))
  }

  // MARK: - Service codegen

  private func generateService(
    options: GeneratorOptions = GeneratorOptions()
  ) throws -> String {
    try generate(
      DefinitionDescriptor(
        kind: .struct, name: "GetUserRequest", fqn: "test.GetUserRequest",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "id", type: TypeDescriptor(kind: .uint32))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "User", fqn: "test.User",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "name", type: TypeDescriptor(kind: .string)),
            FieldDescriptor(name: "age", type: TypeDescriptor(kind: .uint32)),
          ],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "ListFriendsRequest", fqn: "test.ListFriendsRequest",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "user_id", type: TypeDescriptor(kind: .uint32))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "ChatService", fqn: "test.ChatService",
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "GetUser",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.GetUserRequest"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.User"),
            methodType: .unary, id: 0xA3B2_C1D0),
          MethodDescriptor(
            name: "ListFriends",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.ListFriendsRequest"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.User"),
            methodType: .serverStream, id: 0xE4F5_A6B7),
        ])
      ),
      options: options
    )
  }

  @Test func serviceDefinitionEnum() throws {
    let code = try generateService()
    #expect(code.contains("enum ChatService: BebopServiceDefinition"))
    #expect(code.contains("enum Method: UInt32, BebopServiceMethod, CaseIterable"))
    #expect(code.contains("case getUser = 0xA3B2C1D0"))
    #expect(code.contains("case listFriends = 0xE4F5A6B7"))
  }

  @Test func serviceMethodName() throws {
    let code = try generateService()
    #expect(code.contains("case .getUser: return \"GetUser\""))
    #expect(code.contains("case .listFriends: return \"ListFriends\""))
  }

  @Test func serviceMethodType() throws {
    let code = try generateService()
    #expect(code.contains("case .getUser: return .unary"))
    #expect(code.contains("case .listFriends: return .serverStream"))
  }

  @Test func serviceMethodTypeUrls() throws {
    let code = try generateService()
    #expect(code.contains("type.bebop.sh/test.GetUserRequest"))
    #expect(code.contains("type.bebop.sh/test.ListFriendsRequest"))
    #expect(code.contains("type.bebop.sh/test.User"))
  }

  @Test func serviceInfo() throws {
    let code = try generateService()
    #expect(code.contains("static let serviceName = \"ChatService\""))
    #expect(code.contains("static let serviceInfo = ServiceInfo("))
    #expect(code.contains("name: \"ChatService\""))
  }

  @Test func serviceMethodLookup() throws {
    let code = try generateService()
    #expect(code.contains("static func method(for id: UInt32) -> Method? { Method(rawValue: id) }"))
  }

  @Test func serviceHandlerProtocol() throws {
    let code = try generateService()
    #expect(code.contains("protocol ChatServiceHandler: BebopHandler"))
    #expect(
      code.contains(
        "func getUser(\n        _ request: GetUserRequest,\n        context: some CallContext\n    ) async throws -> User"
      ))
    #expect(
      code.contains(
        "func listFriends(\n        _ request: ListFriendsRequest,\n        context: some CallContext\n    ) async throws -> AsyncThrowingStream<User, Error>"
      ))
  }

  @Test func serviceHandlerRegistration() throws {
    let code = try generateService()
    #expect(code.contains("extension BebopRouterBuilder"))
    #expect(code.contains("func register(chatService handler: some ChatServiceHandler)"))
    #expect(code.contains("register(ChatService.self"))
  }

  @Test func serviceClientStub() throws {
    let code = try generateService()
    #expect(code.contains("struct ChatServiceClient<C: BebopChannel>: Sendable"))
    #expect(code.contains("let channel: C"))
    // Unary full request method
    #expect(
      code.contains(
        "func getUser(\n        _ request: GetUserRequest,\n        options: CallOptions = .default\n    ) async throws -> User"
      ))
    // Server stream full request method
    #expect(
      code.contains(
        "func listFriends(\n        _ request: ListFriendsRequest,\n        options: CallOptions = .default\n    ) async throws -> AsyncThrowingStream<User, Error>"
      ))
  }

  @Test func serviceClientDeconstructedUnary() throws {
    let code = try generateService()
    // GetUserRequest has 1 field (id: UInt32), so deconstructed overload should exist
    #expect(
      code.contains(
        "func getUser(\n        id: UInt32,\n        options: CallOptions = .default\n    ) async throws -> User"
      ))
  }

  @Test func serviceClientDeconstructedServerStream() throws {
    let code = try generateService()
    // ListFriendsRequest has 1 field (user_id: UInt32)
    #expect(
      code.contains(
        "func listFriends(\n        userId: UInt32,\n        options: CallOptions = .default\n    ) async throws -> AsyncThrowingStream<User, Error>"
      ))
  }

  @Test func serviceBatchAccessor() throws {
    let code = try generateService()
    #expect(code.contains("struct ChatService_Batch<C: BebopChannel>"))
    #expect(code.contains("let batch: Batch<C>"))
    #expect(
      code.contains(
        "func getUser(_ request: GetUserRequest) -> CallRef<User>"))
    #expect(
      code.contains(
        "func listFriends(_ request: ListFriendsRequest) -> StreamRef<User>"))
    #expect(code.contains("extension Batch"))
    #expect(code.contains("var chatService: ChatService_Batch<Channel>"))
  }

  @Test func serviceBatchDeconstructed() throws {
    let code = try generateService()
    #expect(code.contains("func getUser(id: UInt32) -> CallRef<User>"))
    #expect(code.contains("func listFriends(userId: UInt32) -> StreamRef<User>"))
  }

  @Test func serviceBatchForwarding() throws {
    let code = try generateService()
    #expect(
      code.contains(
        "func getUser<T: BebopRecord>(forwarding ref: CallRef<T>) -> CallRef<User>"))
    #expect(
      code.contains(
        "func listFriends<T: BebopRecord>(forwarding ref: CallRef<T>) -> StreamRef<User>"))
  }

  @Test func serviceClientOnlyMode() throws {
    var opts = GeneratorOptions()
    opts.services = .client
    let code = try generateService(options: opts)
    #expect(code.contains("ChatServiceClient"))
    #expect(code.contains("ChatService_Batch"))
    #expect(!code.contains("ChatServiceHandler"))
    #expect(!code.contains("BebopRouterBuilder"))
  }

  @Test func serviceServerOnlyMode() throws {
    var opts = GeneratorOptions()
    opts.services = .server
    let code = try generateService(options: opts)
    #expect(code.contains("ChatServiceHandler"))
    #expect(code.contains("BebopRouterBuilder"))
    #expect(!code.contains("ChatServiceClient"))
    #expect(!code.contains("ChatService_Batch"))
  }

  @Test func serviceDeconstructedMessageParams() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .message, name: "SearchRequest", fqn: "test.SearchRequest",
        messageDef: MessageDef(fields: [
          FieldDescriptor(name: "query", type: TypeDescriptor(kind: .string), index: 1),
          FieldDescriptor(name: "limit", type: TypeDescriptor(kind: .uint32), index: 2),
        ])
      ),
      DefinitionDescriptor(
        kind: .struct, name: "SearchResult", fqn: "test.SearchResult",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "title", type: TypeDescriptor(kind: .string))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "SearchService", fqn: "test.SearchService",
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "Search",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.SearchRequest"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.SearchResult"),
            methodType: .unary, id: 0x1122_3344)
        ])
      )
    )
    // Message fields become optional params
    #expect(
      code.contains(
        "func search(\n        query: String? = nil, limit: UInt32? = nil,\n        options: CallOptions = .default\n    ) async throws -> SearchResult"
      ))
  }

  @Test func serviceNoDeconstructedWhenTooManyFields() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "BigRequest", fqn: "test.BigRequest",
        structDef: StructDef(
          fields: [
            FieldDescriptor(name: "a", type: TypeDescriptor(kind: .uint32)),
            FieldDescriptor(name: "b", type: TypeDescriptor(kind: .uint32)),
            FieldDescriptor(name: "c", type: TypeDescriptor(kind: .uint32)),
            FieldDescriptor(name: "d", type: TypeDescriptor(kind: .uint32)),
            FieldDescriptor(name: "e", type: TypeDescriptor(kind: .uint32)),
          ],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "Response", fqn: "test.Response",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "ok", type: TypeDescriptor(kind: .bool))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "BigService", fqn: "test.BigService",
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "DoThing",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.BigRequest"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Response"),
            methodType: .unary, id: 0x5566_7788)
        ])
      )
    )
    // Only the full request overload should exist
    #expect(code.contains("func doThing(_ request: BigRequest"))
    // No deconstructed with individual params
    #expect(!code.contains("func doThing(a:"))
  }

  @Test func serviceDocComment() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Req", fqn: "test.Req",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "id", type: TypeDescriptor(kind: .uint32))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "Res", fqn: "test.Res",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "ok", type: TypeDescriptor(kind: .bool))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "DocService", fqn: "test.DocService",
        documentation: "A documented service.",
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "Ping",
            documentation: "Check health.",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.Req"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Res"),
            methodType: .unary, id: 0x1234)
        ])
      )
    )
    // Service-level doc on the enum
    #expect(
      code.contains("/// A documented service.\npublic enum DocService: BebopServiceDefinition"))
    // Method-level doc on handler protocol
    #expect(code.contains("/// Check health.\n    func ping("))
    // Method-level doc on client stub
    #expect(code.contains("/// Check health.\n    public func ping("))
  }

  @Test func serviceDeprecated() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Req", fqn: "test.Req",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "id", type: TypeDescriptor(kind: .uint32))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .struct, name: "Res", fqn: "test.Res",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "ok", type: TypeDescriptor(kind: .bool))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "OldService", fqn: "test.OldService",
        decorators: [
          DecoratorUsage(
            fqn: "deprecated",
            args: [
              DecoratorArg(
                name: "", value: LiteralValue(kind: .string, stringValue: "use NewService"))
            ])
        ],
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "DoThing",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.Req"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Res"),
            methodType: .unary, id: 0x5678,
            decorators: [DecoratorUsage(fqn: "deprecated")])
        ])
      )
    )
    // Service-level deprecated on the enum
    #expect(
      code.contains(
        "@available(*, deprecated, message: \"use NewService\")\npublic enum OldService: BebopServiceDefinition"
      ))
    // Method-level deprecated on handler protocol
    #expect(code.contains("@available(*, deprecated)\n    func doThing("))
    // Method-level deprecated on client stub
    #expect(code.contains("@available(*, deprecated)\n    public func doThing("))
  }

  @Test func serviceMethodTypeMapping() throws {
    let code = try generate(
      DefinitionDescriptor(
        kind: .struct, name: "Msg", fqn: "test.Msg",
        structDef: StructDef(
          fields: [FieldDescriptor(name: "data", type: TypeDescriptor(kind: .string))],
          isMutable: false)
      ),
      DefinitionDescriptor(
        kind: .service, name: "AllTypes", fqn: "test.AllTypes",
        serviceDef: ServiceDef(methods: [
          MethodDescriptor(
            name: "Unary",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            methodType: .unary, id: 1),
          MethodDescriptor(
            name: "ServerStream",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            methodType: .serverStream, id: 2),
          MethodDescriptor(
            name: "ClientStream",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            methodType: .clientStream, id: 3),
          MethodDescriptor(
            name: "DuplexStream",
            requestType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            responseType: TypeDescriptor(kind: .defined, definedFqn: "test.Msg"),
            methodType: .duplexStream, id: 4),
        ])
      )
    )
    #expect(code.contains("case .unary: return .unary"))
    #expect(code.contains("case .serverStream: return .serverStream"))
    #expect(code.contains("case .clientStream: return .clientStream"))
    #expect(code.contains("case .duplexStream: return .duplexStream"))

    // Client stream handler: receives request stream, returns response
    #expect(
      code.contains(
        "func clientStream(\n        _ requests: AsyncThrowingStream<Msg, Error>,\n        context: some CallContext\n    ) async throws -> Msg"
      ))
    // Duplex stream handler: receives request stream, returns response stream
    #expect(
      code.contains(
        "func duplexStream(\n        _ requests: AsyncThrowingStream<Msg, Error>,\n        context: some CallContext\n    ) async throws -> AsyncThrowingStream<Msg, Error>"
      ))
  }
}
