// Code generated by bebopc-gen-swift. DO NOT EDIT.
// source: /Users/andrew/projects/bebop-vnext/plugins/swift/Tests/SwiftBebopTests/test_service.bop
// bebopc 0.1.0
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// The Bebop compiler and runtime are licensed under the Apache License,
// Version 2.0. You may obtain a copy of the License at:
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE
// swiftlint:disable all

import SwiftBebop
// @@bebop_insertion_point(imports)

public struct EchoRequest: BebopRecord, BebopReflectable {
    public let value: String

    enum CodingKeys: String, CodingKey {
        case value
    }

    public init(value: String) {
        self.value = value
    }

    public static func decode(from reader: inout BebopReader) throws -> EchoRequest {
        // @@bebop_insertion_point(decode_start:EchoRequest)
        let value = try reader.readString()
        // @@bebop_insertion_point(decode_end:EchoRequest)
        return EchoRequest(value: value)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:EchoRequest)
        writer.writeString(value)
        // @@bebop_insertion_point(encode_end:EchoRequest)
    }

    public var encodedSize: Int {
        var size = 0
        size += (4 + value.utf8.count + 1)
        return size
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "EchoRequest",
        fqn: "EchoRequest",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "value",
                    index: 0,
                    typeName: "String"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:EchoRequest)
}

public struct EchoResponse: BebopRecord, BebopReflectable {
    public let value: String

    enum CodingKeys: String, CodingKey {
        case value
    }

    public init(value: String) {
        self.value = value
    }

    public static func decode(from reader: inout BebopReader) throws -> EchoResponse {
        // @@bebop_insertion_point(decode_start:EchoResponse)
        let value = try reader.readString()
        // @@bebop_insertion_point(decode_end:EchoResponse)
        return EchoResponse(value: value)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:EchoResponse)
        writer.writeString(value)
        // @@bebop_insertion_point(encode_end:EchoResponse)
    }

    public var encodedSize: Int {
        var size = 0
        size += (4 + value.utf8.count + 1)
        return size
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "EchoResponse",
        fqn: "EchoResponse",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "value",
                    index: 0,
                    typeName: "String"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:EchoResponse)
}

public struct CountRequest: BebopRecord, BebopReflectable {
    public let n: UInt32

    enum CodingKeys: String, CodingKey {
        case n
    }

    public init(n: UInt32) {
        self.n = n
    }

    public static func decode(from reader: inout BebopReader) throws -> CountRequest {
        // @@bebop_insertion_point(decode_start:CountRequest)
        let n = try reader.readUInt32()
        // @@bebop_insertion_point(decode_end:CountRequest)
        return CountRequest(n: n)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:CountRequest)
        writer.writeUInt32(n)
        // @@bebop_insertion_point(encode_end:CountRequest)
    }

    public var encodedSize: Int { 4 }

    public static let bebopReflection = BebopTypeReflection(
        name: "CountRequest",
        fqn: "CountRequest",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "n",
                    index: 0,
                    typeName: "UInt32"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:CountRequest)
}

public struct CountResponse: BebopRecord, BebopReflectable {
    public let i: UInt32

    enum CodingKeys: String, CodingKey {
        case i
    }

    public init(i: UInt32) {
        self.i = i
    }

    public static func decode(from reader: inout BebopReader) throws -> CountResponse {
        // @@bebop_insertion_point(decode_start:CountResponse)
        let i = try reader.readUInt32()
        // @@bebop_insertion_point(decode_end:CountResponse)
        return CountResponse(i: i)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:CountResponse)
        writer.writeUInt32(i)
        // @@bebop_insertion_point(encode_end:CountResponse)
    }

    public var encodedSize: Int { 4 }

    public static let bebopReflection = BebopTypeReflection(
        name: "CountResponse",
        fqn: "CountResponse",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
                BebopFieldReflection(
                    name: "i",
                    index: 0,
                    typeName: "UInt32"
                )
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:CountResponse)
}

/// Widget inventory service.
public enum WidgetService: BebopServiceDefinition {
    public enum Method: UInt32, BebopServiceMethod, CaseIterable {
        case getWidget = 0xA3F73AA7
        case listWidgets = 0xBB7F3698
        case uploadWidgets = 0xC1A30C3B
        case syncWidgets = 0x317F5C17

        public var name: String {
            switch self {
                case .getWidget: return "GetWidget"
                case .listWidgets: return "ListWidgets"
                case .uploadWidgets: return "UploadWidgets"
                case .syncWidgets: return "SyncWidgets"
            }
        }

        public var methodType: MethodType {
            switch self {
                case .getWidget: return .unary
                case .listWidgets: return .serverStream
                case .uploadWidgets: return .clientStream
                case .syncWidgets: return .duplexStream
            }
        }

        public var requestTypeUrl: String {
            switch self {
                case .getWidget: return "type.bebop.sh/EchoRequest"
                case .listWidgets: return "type.bebop.sh/CountRequest"
                case .uploadWidgets: return "type.bebop.sh/EchoRequest"
                case .syncWidgets: return "type.bebop.sh/EchoRequest"
            }
        }

        public var responseTypeUrl: String {
            switch self {
                case .getWidget: return "type.bebop.sh/EchoResponse"
                case .listWidgets: return "type.bebop.sh/CountResponse"
                case .uploadWidgets: return "type.bebop.sh/EchoResponse"
                case .syncWidgets: return "type.bebop.sh/EchoResponse"
            }
        }
    }

    public static let serviceName = "WidgetService"
    public static let serviceInfo = ServiceInfo(
        name: "WidgetService",
        methods: [
            MethodInfo(
                name: "GetWidget",
                methodId: 0xA3F73AA7,
                methodType: .unary,
                requestTypeUrl: "type.bebop.sh/EchoRequest",
                responseTypeUrl: "type.bebop.sh/EchoResponse"
            ),
            MethodInfo(
                name: "ListWidgets",
                methodId: 0xBB7F3698,
                methodType: .serverStream,
                requestTypeUrl: "type.bebop.sh/CountRequest",
                responseTypeUrl: "type.bebop.sh/CountResponse"
            ),
            MethodInfo(
                name: "UploadWidgets",
                methodId: 0xC1A30C3B,
                methodType: .clientStream,
                requestTypeUrl: "type.bebop.sh/EchoRequest",
                responseTypeUrl: "type.bebop.sh/EchoResponse"
            ),
            MethodInfo(
                name: "SyncWidgets",
                methodId: 0x317F5C17,
                methodType: .duplexStream,
                requestTypeUrl: "type.bebop.sh/EchoRequest",
                responseTypeUrl: "type.bebop.sh/EchoResponse"
            )
        ]
    )
    public static func method(for id: UInt32) -> Method? { Method(rawValue: id) }
    // @@bebop_insertion_point(service_scope:WidgetService)
}

public protocol WidgetServiceHandler: BebopHandler {
    /// Echo back the input.
    func getWidget(
        _ request: EchoRequest,
        context: some CallContext
    ) async throws -> EchoResponse

    /// Stream count responses.
    func listWidgets(
        _ request: CountRequest,
        context: some CallContext
    ) async throws -> AsyncThrowingStream<CountResponse, Error>

    @available(*, deprecated, message: "use CollectV2")
    func uploadWidgets(
        _ requests: AsyncThrowingStream<EchoRequest, Error>,
        context: some CallContext
    ) async throws -> EchoResponse

    /// Bidirectional echo.
    func syncWidgets(
        _ requests: AsyncThrowingStream<EchoRequest, Error>,
        context: some CallContext
    ) async throws -> AsyncThrowingStream<EchoResponse, Error>
}

extension BebopRouterBuilder {
    public func register(widgetService handler: some WidgetServiceHandler) {
        register(WidgetService.self, unary: { method, context, payload in
            switch method {
                case .getWidget:
                    let req = try EchoRequest.decode(from: payload)
                    let res = try await handler.getWidget(req, context: context)
                    return res.serializedData()
                default: throw BebopRpcError(code: .unimplemented)
            }
        }, serverStream: { method, context, payload in
            switch method {
                case .listWidgets:
                    let req = try CountRequest.decode(from: payload)
                    let typed = try await handler.listWidgets(req, context: context)
                    return AsyncThrowingStream<[UInt8], Error> { c in
                        let task = Task {
                            do {
                                for try await item in typed {
                                    try Task.checkCancellation()
                                    if let d = context.deadline, d.isPast {
                                        throw BebopRpcError(code: .deadlineExceeded)
                                    }
                                    c.yield(item.serializedData())
                                }
                                c.finish()
                            } catch {
                                c.finish(throwing: error)
                            }
                        }
                        c.onTermination = { _ in task.cancel() }
                    }
                default: throw BebopRpcError(code: .unimplemented)
            }
        }, clientStream: { method, context in
            switch method {
                case .uploadWidgets:
                    let (stream, continuation) = AsyncThrowingStream.makeStream(of: EchoRequest.self)
                    let task = Task {
                        defer { continuation.finish() }
                        return try await handler.uploadWidgets(stream, context: context)
                    }
                    return (
                        send: { bytes in
                            if let d = context.deadline, d.isPast {
                                throw BebopRpcError(code: .deadlineExceeded)
                            }
                            let req = try EchoRequest.decode(from: bytes)
                            if case .terminated = continuation.yield(req) {
                                throw BebopRpcError(code: .cancelled, detail: "stream terminated")
                            }
                        },
                        finish: {
                            continuation.finish()
                            return try await task.value.serializedData()
                        }
                    )
                default: throw BebopRpcError(code: .unimplemented)
            }
        }, duplexStream: { method, context in
            switch method {
                case .syncWidgets:
                    let (stream, continuation) = AsyncThrowingStream.makeStream(of: EchoRequest.self)
                    let typedResponses = try await handler.syncWidgets(stream, context: context)
                    let rawResponses = AsyncThrowingStream<[UInt8], Error> { c in
                        let task = Task {
                            do {
                                for try await item in typedResponses {
                                    try Task.checkCancellation()
                                    if let d = context.deadline, d.isPast {
                                        throw BebopRpcError(code: .deadlineExceeded)
                                    }
                                    c.yield(item.serializedData())
                                }
                                c.finish()
                            } catch {
                                c.finish(throwing: error)
                            }
                        }
                        c.onTermination = { _ in
                            task.cancel()
                            continuation.finish()
                        }
                    }
                    return (
                        send: { bytes in
                            if let d = context.deadline, d.isPast {
                                throw BebopRpcError(code: .deadlineExceeded)
                            }
                            let req = try EchoRequest.decode(from: bytes)
                            if case .terminated = continuation.yield(req) {
                                throw BebopRpcError(code: .cancelled, detail: "stream terminated")
                            }
                        },
                        finish: { continuation.finish() },
                        responses: rawResponses
                    )
                default: throw BebopRpcError(code: .unimplemented)
            }
        })
    }
}

public struct WidgetServiceClient<C: BebopChannel>: Sendable {
    public let channel: C

    public init(channel: C) { self.channel = channel }

    /// Echo back the input.
    public func getWidget(
        _ request: EchoRequest,
        options: CallOptions = .default
    ) async throws -> EchoResponse {
        let data = try await channel.unary(
            method: 0xA3F73AA7,
            request: request.serializedData(),
            options: options
        )
        return try EchoResponse.decode(from: data)
    }

    public func getWidget(
        value: String,
        options: CallOptions = .default
    ) async throws -> EchoResponse {
        try await getWidget(EchoRequest(value: value), options: options)
    }

    /// Stream count responses.
    public func listWidgets(
        _ request: CountRequest,
        options: CallOptions = .default
    ) async throws -> AsyncThrowingStream<CountResponse, Error> {
        let raw = try await channel.serverStream(
            method: 0xBB7F3698,
            request: request.serializedData(),
            options: options
        )
        return raw.decode(CountResponse.self)
    }

    public func listWidgets(
        n: UInt32,
        options: CallOptions = .default
    ) async throws -> AsyncThrowingStream<CountResponse, Error> {
        try await listWidgets(CountRequest(n: n), options: options)
    }

    @available(*, deprecated, message: "use CollectV2")
    public func uploadWidgets(
        options: CallOptions = .default,
        body: (
            _ send: @Sendable (EchoRequest) async throws -> Void
        ) async throws -> Void
    ) async throws -> EchoResponse {
        let (rawSend, rawFinish) = try await channel.clientStream(
            method: 0xC1A30C3B,
            options: options
        )
        try await body({ try await rawSend($0.serializedData()) })
        return try await EchoResponse.decode(from: rawFinish())
    }

    /// Bidirectional echo.
    public func syncWidgets(
        options: CallOptions = .default,
        body: (
            _ send: @Sendable (EchoRequest) async throws -> Void,
            _ finish: @Sendable () async throws -> Void,
            _ responses: AsyncThrowingStream<EchoResponse, Error>
        ) async throws -> Void
    ) async throws {
        let (rawSend, rawFinish, rawResponses) = try await channel.duplexStream(
            method: 0x317F5C17,
            options: options
        )
        do {
            try await body(
                { try await rawSend($0.serializedData()) },
                rawFinish,
                rawResponses.decode(EchoResponse.self)
            )
        } catch {
            try? await rawFinish()
            throw error
        }
    }
}

public struct WidgetService_Batch<C: BebopChannel> {
    public let batch: Batch<C>

    @discardableResult
    public func getWidget(_ request: EchoRequest) -> CallRef<EchoResponse> {
        batch.addUnary(methodId: 0xA3F73AA7, request: request)
    }

    @discardableResult
    public func getWidget(value: String) -> CallRef<EchoResponse> {
        getWidget(EchoRequest(value: value))
    }

    @discardableResult
    public func getWidget<T: BebopRecord>(forwarding ref: CallRef<T>) -> CallRef<EchoResponse> {
        batch.addUnary(methodId: 0xA3F73AA7, forwardingFrom: ref.callId)
    }

    @discardableResult
    public func listWidgets(_ request: CountRequest) -> StreamRef<CountResponse> {
        batch.addServerStream(methodId: 0xBB7F3698, request: request)
    }

    @discardableResult
    public func listWidgets(n: UInt32) -> StreamRef<CountResponse> {
        listWidgets(CountRequest(n: n))
    }

    @discardableResult
    public func listWidgets<T: BebopRecord>(forwarding ref: CallRef<T>) -> StreamRef<CountResponse> {
        batch.addServerStream(methodId: 0xBB7F3698, forwardingFrom: ref.callId)
    }
}

extension Batch {
    public var widgetService: WidgetService_Batch<Channel> { WidgetService_Batch(batch: self) }
}

// @@bebop_insertion_point(eof)
