import BebopPlugin
import Foundation

func readAllStdin() -> [UInt8] {
    var buf = [UInt8]()
    let chunk = 65536
    let handle = FileHandle.standardInput
    while true {
        let data = handle.readData(ofLength: chunk)
        if data.isEmpty { break }
        buf.append(contentsOf: data)
    }
    return buf
}

func parseOptions(_ hostOptions: [String: String]?) -> GeneratorOptions {
    var opts = GeneratorOptions()
    guard let hostOptions else { return opts }
    if let vis = hostOptions["Visibility"] {
        switch vis.lowercased() {
        case "internal": opts.visibility = "internal "
        case "package": opts.visibility = "package "
        case "public": opts.visibility = "public "
        default: break
        }
    }
    return opts
}

func run() throws {
    let input = readAllStdin()
    guard !input.isEmpty else {
        throw GeneratorError.emptyInput
    }

    let request = try PluginRequest.decode(from: input)

    guard let filesToGenerate = request.filesToGenerate else {
        throw CodegenError.malformedDefinition("request missing filesToGenerate")
    }
    guard let schemas = request.schemas else {
        throw CodegenError.malformedDefinition("request missing schemas")
    }

    let fileSet = Set(filesToGenerate)
    try NamingPolicy.registerSchemas(schemas)
    let options = parseOptions(request.hostOptions)
    let generator = SwiftGenerator(options: options)
    let response = ResponseBuilder()

    var usesFixedArray = false
    for schema in schemas {
        guard let path = schema.path, fileSet.contains(path) else {
            continue
        }

        let fileName = URL(fileURLWithPath: path)
            .deletingPathExtension()
            .lastPathComponent + ".bb.swift"

        let code = try generator.generate(schema: schema)
        response.addFile(name: fileName, content: code)

        if !usesFixedArray, let defs = schema.definitions {
            usesFixedArray = defs.contains(where: { usesFixedArrayType($0) })
        }
    }

    if usesFixedArray {
        response.addFile(name: "InlineArrayConformances.bb.swift", content: inlineArrayConformances)
    }

    let output = try response.encode()
    FileHandle.standardOutput.write(Data(output))
}

do {
    try run()
} catch {
    let response = ResponseBuilder()
    response.setError("bebopc-gen-swift: \(error)")
    if let output = try? response.encode() {
        FileHandle.standardOutput.write(Data(output))
    } else {
        FileHandle.standardError.write(
            Data("bebopc-gen-swift: \(error)\n".utf8)
        )
        exit(1)
    }
}

enum GeneratorError: Error {
    case emptyInput
}

func usesFixedArrayType(_ def: DefinitionDescriptor) -> Bool {
    if let fields = def.structDef?.fields ?? def.messageDef?.fields {
        for f in fields {
            if f.type?.kind == .fixedArray { return true }
        }
    }
    if let nested = def.nested {
        if nested.contains(where: { usesFixedArrayType($0) }) { return true }
    }
    return false
}

// Emitted once per generated module when any schema uses fixed-size arrays.
// Will be unnecessary once SE-0453 adds these to stdlib.
let inlineArrayConformances = """
// Auto-generated by bebopc-gen-swift. Do not edit.
// Retroactive InlineArray conformances — will be removed when SE-0453 lands.
// swiftlint:disable all
import SwiftBebop

extension InlineArray: @retroactive Equatable where Element: Equatable {
    public static func == (lhs: Self, rhs: Self) -> Bool {
        for i in 0..<count {
            if lhs[i] != rhs[i] { return false }
        }
        return true
    }
}

extension InlineArray: @retroactive Hashable where Element: Hashable {
    public func hash(into hasher: inout Hasher) {
        for i in 0..<count { hasher.combine(self[i]) }
    }
}

extension InlineArray: @retroactive Encodable where Element: Encodable {
    public func encode(to encoder: Encoder) throws {
        var container = encoder.unkeyedContainer()
        for i in 0..<count { try container.encode(self[i]) }
    }
}

extension InlineArray: @retroactive Decodable where Element: Decodable {
    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        self = try InlineArray { _ in try container.decode(Element.self) }
    }
}
"""
