import Foundation
import SwiftSyntax
import SwiftSyntaxBuilder
import BebopPlugin

struct GeneratorOptions {
    var visibility: String = "public "
}

struct SwiftGenerator {
    let options: GeneratorOptions

    private static let wellKnownFQNs: Set<String> = ["bebop.Any", "bebop.TYPE_URL_PREFIX"]

    func generate(schema: SchemaDescriptor) throws -> String {
        var declarations: [DeclSyntax] = [
            "import SwiftBebop",
            "import Foundation",
        ]

        if let definitions = schema.definitions {
            for def in definitions {
                declarations.append(contentsOf: try generateDefinition(def))
            }
        }

        let source = SourceFileSyntax {
            for decl in declarations {
                decl
            }
        }

        let formatted = source.formatted().description
        return "// Auto-generated by bebopc-gen-swift. Do not edit.\n// swiftlint:disable all\n"
            + formatted.trimmingCharacters(in: .newlines) + "\n"
    }

    func generateDefinition(_ def: DefinitionDescriptor) throws -> [DeclSyntax] {
        if let fqn = def.fqn, Self.wellKnownFQNs.contains(fqn) { return [] }

        var nested: [DeclSyntax] = []
        if let children = def.nested {
            for child in children {
                nested.append(contentsOf: try generateDefinition(child))
            }
        }

        guard let kind = def.kind else {
            throw CodegenError.malformedDefinition("definition missing kind")
        }
        switch kind {
        case .enum: return try GenerateEnum.generate(def, options: options)
        case .struct: return try GenerateStruct.generate(def, nested: nested, options: options)
        case .message: return try GenerateMessage.generate(def, nested: nested, options: options)
        case .union: return try GenerateUnion.generate(def, nested: nested, options: options)
        case .const: return try GenerateConst.generate(def, options: options)
        case .service, .decorator: return []
        default:
            throw CodegenError.malformedDefinition("unknown definition kind \(kind.rawValue)")
        }
    }
}

// MARK: - Codegen Helpers

func docComment(_ doc: String?) -> String {
    guard let doc, !doc.isEmpty else { return "" }
    return doc.split(separator: "\n", omittingEmptySubsequences: false)
        .map { "/// \($0)" }
        .joined(separator: "\n") + "\n"
}

func deprecatedAttribute(_ decorators: [DecoratorUsage]?) -> String? {
    guard let dep = decorators?.first(where: { $0.fqn == "deprecated" }) else {
        return nil
    }
    if let arg = dep.args?.first, arg.value.kind == .string,
       let msg = arg.value.stringValue, !msg.isEmpty {
        let escaped = msg.replacingOccurrences(of: "\"", with: "\\\"")
        return "@available(*, deprecated, message: \"\(escaped)\")"
    }
    return "@available(*, deprecated)"
}

func declPrefix(doc: String?, decorators: [DecoratorUsage]?) -> String {
    var prefix = docComment(doc)
    if let attr = deprecatedAttribute(decorators) {
        prefix += attr + "\n"
    }
    return prefix
}

func quoted(_ s: String) -> String {
    let escaped = s
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

func effectiveVisibility(for def: DefinitionDescriptor, options: GeneratorOptions) -> String {
    def.visibility == .local ? "internal " : options.visibility
}

func codingKeysDecl(_ fields: [(swiftName: String, originalName: String)]) -> String {
    let cases = fields.map { (swift, original) in
        swift == original ? "case \(swift)" : "case \(swift) = \(quoted(original))"
    }.joined(separator: "\n")
    return "enum CodingKeys: String, CodingKey {\n\(cases)\n}"
}
