import BebopPlugin

enum ServiceGenMode: String {
    case none
    case client
    case server
    case both
}

struct GeneratorOptions {
    var visibility: String = "public "
    var services: ServiceGenMode = .both
}

struct SwiftGenerator {
    let options: GeneratorOptions
    let compilerVersion: Version?

    private static let wellKnownFQNs: Set<String> = [
        "bebop.Any", "bebop.Empty", "bebop.TYPE_URL_PREFIX",
    ]

    func generate(schema: SchemaDescriptor) throws -> String {
        var declarations = [
            "import SwiftBebop\n// @@bebop_insertion_point(imports)",
        ]

        if let definitions = schema.definitions {
            for def in definitions {
                try declarations.append(contentsOf: generateDefinition(def))
            }
            if definitions.contains(where: { usesFixedArrayType($0) }) {
                declarations.insert(inlineArrayHelpers, at: 1)
            }
        }

        let body = declarations.joined(separator: "\n\n")
        return generatedNotice(schema: schema) + body
            + "\n\n// @@bebop_insertion_point(eof)\n"
    }

    private func generatedNotice(schema: SchemaDescriptor) -> String {
        var lines: [String] = []
        lines.append("// Code generated by bebopc-gen-swift. DO NOT EDIT.")
        lines.append("// source: \(schema.path ?? "unknown")")
        if let v = compilerVersion {
            if v.suffix.isEmpty {
                lines.append("// bebopc \(v.major).\(v.minor).\(v.patch)")
            } else {
                lines.append("// bebopc \(v.major).\(v.minor).\(v.patch)-\(v.suffix)")
            }
        }
        if let edition = schema.edition, edition == .edition2026 {
            lines.append("// edition 2026")
        }
        lines.append("//")
        lines.append("// This file requires the Bebop runtime library.")
        lines.append("// https://github.com/6over3/bebop")
        lines.append("//")
        lines.append("// The Bebop compiler and runtime are licensed under the Apache License,")
        lines.append("// Version 2.0. You may obtain a copy of the License at:")
        lines.append("// https://www.apache.org/licenses/LICENSE-2.0")
        lines.append("//")
        lines.append("// SPDX-License-Identifier: Apache-2.0")
        lines.append("// Copyright (c) 6OVER3 INSTITUTE")
        lines.append("// swiftlint:disable all")
        lines.append("")
        return lines.joined(separator: "\n") + "\n"
    }

    func generateDefinition(_ def: DefinitionDescriptor) throws -> [String] {
        if let fqn = def.fqn, Self.wellKnownFQNs.contains(fqn) { return [] }

        let previousShadowed = TypeMapper.shadowedNames
        if let children = def.nested {
            let nestedNames = Set(children.compactMap(\.name))
            TypeMapper.shadowedNames = previousShadowed.union(
                nestedNames.intersection(TypeMapper.swiftPrimitiveNames)
            )
        }

        var nested: [String] = []
        if let children = def.nested {
            for child in children {
                try nested.append(contentsOf: generateDefinition(child))
            }
        }

        guard let kind = def.kind else {
            TypeMapper.shadowedNames = previousShadowed
            throw CodegenError.malformedDefinition("definition missing kind")
        }
        let result: [String]
        switch kind {
        case .enum: result = try GenerateEnum.generate(def, options: options)
        case .struct: result = try GenerateStruct.generate(def, nested: nested, options: options)
        case .message: result = try GenerateMessage.generate(def, nested: nested, options: options)
        case .union: result = try GenerateUnion.generate(def, nested: nested, options: options)
        case .const: result = try GenerateConst.generate(def, options: options)
        case .service: result = try GenerateService.generate(def, options: options)
        case .decorator: result = []
        default:
            TypeMapper.shadowedNames = previousShadowed
            throw CodegenError.malformedDefinition("unknown definition kind \(kind.rawValue)")
        }
        TypeMapper.shadowedNames = previousShadowed
        return result
    }
}

// MARK: - Codegen Helpers

func docComment(_ doc: String?) -> String {
    guard let doc, !doc.isEmpty else { return "" }
    return doc.split(separator: "\n", omittingEmptySubsequences: false)
        .map { "/// \($0)" }
        .joined(separator: "\n") + "\n"
}

func deprecatedAttribute(_ decorators: [DecoratorUsage]?) -> String? {
    guard let dep = decorators?.first(where: { $0.fqn == "deprecated" }) else {
        return nil
    }
    if let arg = dep.args?.first, arg.value.kind == .string,
       let msg = arg.value.stringValue, !msg.isEmpty
    {
        let escaped = msg.replacingOccurrences(of: "\"", with: "\\\"")
        return "@available(*, deprecated, message: \"\(escaped)\")"
    }
    return "@available(*, deprecated)"
}

func declPrefix(doc: String?, decorators: [DecoratorUsage]?) -> String {
    var prefix = docComment(doc)
    if let attr = deprecatedAttribute(decorators) {
        prefix += attr + "\n"
    }
    return prefix
}

func quoted(_ s: String) -> String {
    let escaped =
        s
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

func effectiveVisibility(for def: DefinitionDescriptor, options: GeneratorOptions) -> String {
    def.visibility == .local ? "internal " : options.visibility
}

func codingKeysDecl(_ fields: [(swiftName: String, originalName: String)]) -> String {
    let cases = fields.map { swift, original in
        swift == original ? "    case \(swift)" : "    case \(swift) = \(quoted(original))"
    }.joined(separator: "\n")
    let rawType = TypeMapper.unshadow("String")
    return "enum CodingKeys: \(rawType), CodingKey {\n\(cases)\n}"
}

func fixedArrayEncodeLines(
    type: TypeDescriptor, container: String, value: String, depth: Int = 0
) throws -> [String] {
    let size = type.fixedArraySize!
    let elem = type.fixedArrayElement!
    let idx = "i\(depth)"

    if elem.kind == .fixedArray {
        let innerContainer = "c\(depth)"
        let innerLines = try fixedArrayEncodeLines(
            type: elem, container: innerContainer, value: "\(value)[\(idx)]", depth: depth + 1
        )
        return [
            "for \(idx) in 0..<\(size) {",
            "    var \(innerContainer) = \(container).nestedUnkeyedContainer()",
        ] + innerLines.map { "    " + $0 } + ["}"]
    }
    return ["for \(idx) in 0..<\(size) { try \(container).encode(\(value)[\(idx)]) }"]
}

func fixedArrayDecodeExpr(
    type: TypeDescriptor, container: String, depth: Int = 0
) throws -> String {
    let size = type.fixedArraySize!
    let elem = type.fixedArrayElement!
    let elemSwiftType = try TypeMapper.swiftType(for: elem)
    let fullType = "InlineArray<\(size), \(elemSwiftType)>"

    if elem.kind == .fixedArray {
        let innerContainer = "c\(depth)"
        let innerExpr = try fixedArrayDecodeExpr(
            type: elem, container: innerContainer, depth: depth + 1
        )
        return "\(fullType) { _ in var \(innerContainer) = try \(container).nestedUnkeyedContainer(); return try \(innerExpr) }"
    }
    return "\(fullType) { _ in try \(container).decode(\(elemSwiftType).self) }"
}

func indent(_ text: String, _ level: Int = 1) -> String {
    let pad = String(repeating: "    ", count: level)
    return text.split(separator: "\n", omittingEmptySubsequences: false)
        .map { $0.isEmpty ? "" : pad + $0 }
        .joined(separator: "\n")
}

private let inlineArrayHelpers = """
fileprivate func == <let N: Int, Element: Equatable>(
    lhs: InlineArray<N, Element>, rhs: InlineArray<N, Element>
) -> Bool {
    for i in 0..<N { if lhs[i] != rhs[i] { return false } }
    return true
}

fileprivate func == <let N: Int, let M: Int, Element: Equatable>(
    lhs: InlineArray<N, InlineArray<M, Element>>, rhs: InlineArray<N, InlineArray<M, Element>>
) -> Bool {
    for i in 0..<N { for j in 0..<M { if lhs[i][j] != rhs[i][j] { return false } } }
    return true
}

fileprivate func == <let N: Int, Element: Equatable>(
    lhs: InlineArray<N, Element>?, rhs: InlineArray<N, Element>?
) -> Bool {
    switch (lhs, rhs) {
    case (.none, .none): return true
    case let (.some(l), .some(r)): return l == r
    default: return false
    }
}

fileprivate func == <let N: Int, let M: Int, Element: Equatable>(
    lhs: InlineArray<N, InlineArray<M, Element>>?, rhs: InlineArray<N, InlineArray<M, Element>>?
) -> Bool {
    switch (lhs, rhs) {
    case (.none, .none): return true
    case let (.some(l), .some(r)): return l == r
    default: return false
    }
}

extension Hasher {
    fileprivate mutating func combine<let N: Int, Element: Hashable>(
        _ value: InlineArray<N, Element>
    ) {
        for i in 0..<N { combine(value[i]) }
    }

    fileprivate mutating func combine<let N: Int, let M: Int, Element: Hashable>(
        _ value: InlineArray<N, InlineArray<M, Element>>
    ) {
        for i in 0..<N { for j in 0..<M { combine(value[i][j]) } }
    }

    fileprivate mutating func combine<let N: Int, Element: Hashable>(
        _ value: InlineArray<N, Element>?
    ) {
        switch value {
        case .none: combine(false)
        case .some(let v):
            combine(true)
            for i in 0..<N { combine(v[i]) }
        }
    }

    fileprivate mutating func combine<let N: Int, let M: Int, Element: Hashable>(
        _ value: InlineArray<N, InlineArray<M, Element>>?
    ) {
        switch value {
        case .none: combine(false)
        case .some(let v):
            combine(true)
            for i in 0..<N { for j in 0..<M { combine(v[i][j]) } }
        }
    }
}
"""
