pub mod gen_const;
pub mod gen_enum;
pub mod gen_message;
pub mod gen_service;
pub mod gen_struct;
pub mod gen_union;
pub mod naming;
pub mod type_mapper;

use crate::error::GeneratorError;
use crate::generated::*;

pub struct RustGenerator {
  pub compiler_version: Option<Version>,
}

impl RustGenerator {
  pub fn new(compiler_version: Option<Version>) -> Self {
    Self { compiler_version }
  }

  /// Generate Rust code for a single schema.
  pub fn generate(&self, schema: &SchemaDescriptor) -> Result<String, GeneratorError> {
    let mut output = String::new();

    // File header
    output.push_str("// Code generated by bebopc-gen-rust. DO NOT EDIT.\n");
    if let Some(ref path) = schema.path {
      output.push_str(&format!("// source: {}\n", path));
    }
    if let Some(ref v) = self.compiler_version {
      output.push_str(&format!("// bebopc {}\n", v));
    }
    if let Some(ref edition) = schema.edition {
      if *edition == Edition::EDITION_2026 {
        output.push_str("// edition 2026\n");
      }
    }
    output.push_str("//\n");
    output.push_str("// This file requires the Bebop runtime library.\n");
    output.push_str("// https://github.com/6over3/bebop\n");
    output.push_str("//\n");
    output.push_str("// SPDX-License-Identifier: Apache-2.0\n");
    output.push_str("// Copyright (c) 6OVER3 INSTITUTE\n\n");

    // Use preamble
    output.push_str("#![allow(dead_code, unused_imports)]\n\n");
    output.push_str("use std::collections::HashMap;\n");
    output.push_str("use bebop_runtime::{BebopReader, BebopWriter, DecodeError, F16, BF16};\n\n");

    if let Some(ref definitions) = schema.definitions {
      for def in definitions {
        self.generate_definition(def, &mut output, 0)?;
      }
    }

    Ok(output)
  }

  fn generate_definition(
    &self,
    def: &DefinitionDescriptor,
    output: &mut String,
    depth: usize,
  ) -> Result<(), GeneratorError> {
    let kind = def
      .kind
      .ok_or_else(|| GeneratorError::MalformedDefinition("definition missing kind".into()))?;
    let name = def.name.as_deref().unwrap_or("<unnamed>");
    let fqn = def.fqn.as_deref().unwrap_or("<no fqn>");

    // Log what we're processing
    let indent = "  ".repeat(depth);
    eprintln!(
      "[bebopc-gen-rust] {}{} {} ({})",
      indent,
      kind.name(),
      name,
      fqn,
    );

    match kind {
      DefinitionKind::ENUM => gen_enum::generate(def, output)?,
      DefinitionKind::STRUCT => gen_struct::generate(def, output)?,
      DefinitionKind::MESSAGE => gen_message::generate(def, output)?,
      DefinitionKind::UNION => gen_union::generate(def, output)?,
      DefinitionKind::CONST => gen_const::generate(def, output)?,
      DefinitionKind::SERVICE => gen_service::generate(def, output)?,
      DefinitionKind::DECORATOR => { /* Skip decorator definitions */ }
      _ => {
        eprintln!(
          "[bebopc-gen-rust] {}  WARNING: unknown definition kind {}",
          indent, kind.0
        );
      }
    }

    // Process nested definitions
    if let Some(ref nested) = def.nested {
      for child in nested {
        self.generate_definition(child, output, depth + 1)?;
      }
    }

    Ok(())
  }
}

/// Emit `///` doc comment lines if documentation is present.
pub fn emit_doc_comment(output: &mut String, doc: &Option<String>) {
  if let Some(ref text) = doc {
    for line in text.lines() {
      output.push_str(&format!("/// {}\n", line));
    }
  }
}

/// Emit `#[deprecated]` attribute if the definition has a `@deprecated` decorator.
pub fn emit_deprecated(output: &mut String, decorators: &Option<Vec<DecoratorUsage>>) {
  if let Some(ref decs) = decorators {
    for dec in decs {
      if dec.fqn.as_deref() == Some("bebop.deprecated") {
        // Check for a message argument
        let msg = dec.args.as_ref().and_then(|args| {
          args.iter().find_map(|arg| {
            if let crate::generated::LiteralValue {
              string_value: Some(ref s),
              ..
            } = arg.value
            {
              Some(s.clone())
            } else {
              None
            }
          })
        });
        if let Some(msg) = msg {
          output.push_str(&format!("#[deprecated(note = \"{}\")]\n", msg));
        } else {
          output.push_str("#[deprecated]\n");
        }
        return;
      }
    }
  }
}
