// Code generated by bebopc-gen-rust. DO NOT EDIT.
// source: /Users/mayfield/vendor/bebop-next/plugins/rust/integration-tests/schemas/no_std_types.bop
// bebopc 0.1.0
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE

#![allow(warnings)]

extern crate alloc;
use alloc::borrow::Cow;
use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use core::mem::size_of;
use bebop_runtime::HashMap;
use bebop_runtime::{BebopReader, BebopWriter, BebopEncode, BebopDecode, BebopFlags, DecodeError, f16, bf16};
use bebop_runtime::wire_size as wire;

/// Fixed-size struct.
#[derive(Debug, Clone)]
pub struct Position {
  pub x: f32,
  pub y: f32,
}

impl Position {
  pub const FIXED_ENCODED_SIZE: usize = size_of::<f32>() + size_of::<f32>();

  pub fn new(x: f32, y: f32) -> Self {
    Self { x, y }
  }
}

impl BebopEncode for Position {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_f32(self.x);
    writer.write_f32(self.y);
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Position {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let x = reader.read_f32()?;
    let y = reader.read_f32()?;
    Ok(Position { x, y })
  }
}

/// Borrowed string in generated Rust (`Cow<'buf, str>`).
#[derive(Debug, Clone)]
pub struct Label<'buf> {
  pub text: Cow<'buf, str>,
}

pub type LabelOwned = Label<'static>;

impl<'buf> Label<'buf> {
  pub fn new(text: impl Into<Cow<'buf, str>>) -> Self {
    let text = text.into();
    Self { text }
  }
}

impl<'buf> Label<'buf> {
  pub fn into_owned(self) -> LabelOwned {
    Label {
      text: Cow::Owned(self.text.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for Label<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_string(&self.text);
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.text.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for Label<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let text = Cow::Borrowed(reader.read_str()?);
    Ok(Label { text })
  }
}

/// Borrowed byte array in generated Rust (`Cow<'buf, [u8]>`).
#[derive(Debug, Clone)]
pub struct Blob<'buf> {
  pub data: Cow<'buf, [u8]>,
}

pub type BlobOwned = Blob<'static>;

impl<'buf> Blob<'buf> {
  pub fn new(data: impl Into<Cow<'buf, [u8]>>) -> Self {
    let data = data.into();
    Self { data }
  }
}

impl<'buf> Blob<'buf> {
  pub fn into_owned(self) -> BlobOwned {
    Blob {
      data: Cow::Owned(self.data.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for Blob<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_byte_array(&self.data);
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::byte_array_size(self.data.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for Blob<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let data = Cow::Borrowed(reader.read_byte_slice()?);
    Ok(Blob { data })
  }
}

/// Message with no map fields.
#[derive(Debug, Clone, Default)]
pub struct Snapshot<'buf> {
  pub id: Option<u32>,
  pub title: Option<Cow<'buf, str>>,
  pub points: Option<Vec<Position>>,
  pub payload: Option<Cow<'buf, [u8]>>,
  pub counts: Option<HashMap<Cow<'buf, str>, u32>>,
}

pub type SnapshotOwned = Snapshot<'static>;

impl<'buf> Snapshot<'buf> {
  pub fn into_owned(self) -> SnapshotOwned {
    Snapshot {
      id: self.id,
      title: self.title.map(|v| Cow::Owned(v.into_owned())),
      points: self.points,
      payload: self.payload.map(|v| Cow::Owned(v.into_owned())),
      counts: self.counts.map(|v| v.into_iter().map(|(_k, _v)| (Cow::Owned(_k.into_owned()), _v)).collect()),
    }
  }
}

impl<'buf> BebopEncode for Snapshot<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(v) = self.id {
      writer.write_tag(1);
      writer.write_u32(v);
    }
    if let Some(ref v) = self.title {
      writer.write_tag(2);
      writer.write_string(&v);
    }
    if let Some(ref v) = self.points {
      writer.write_tag(3);
      writer.write_array(&v, |_w, _el| _el.encode(_w));
    }
    if let Some(ref v) = self.payload {
      writer.write_tag(4);
      writer.write_byte_array(&v);
    }
    if let Some(ref v) = self.counts {
      writer.write_tag(5);
      writer.write_map(&v, |_w, _k, _v| { _w.write_string(&_k); _w.write_u32(*_v); });
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(v) = self.id {
      size += wire::tagged_size(size_of::<u32>());
    }
    if let Some(ref v) = self.title {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let Some(ref v) = self.points {
      size += wire::tagged_size(wire::array_size(v, |_el| _el.encoded_size()));
    }
    if let Some(ref v) = self.payload {
      size += wire::tagged_size(wire::byte_array_size(v.len()));
    }
    if let Some(ref v) = self.counts {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| wire::string_size(_k.len()) + size_of::<u32>()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for Snapshot<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.id = Some(reader.read_u32()?),
        2 => msg.title = Some(Cow::Borrowed(reader.read_str()?)),
        3 => msg.points = Some(reader.read_array(|_r| Position::decode(_r))?),
        4 => msg.payload = Some(Cow::Borrowed(reader.read_byte_slice()?)),
        5 => msg.counts = Some(reader.read_map(|_r| Ok((Ok(Cow::Borrowed(_r.read_str()?))?, _r.read_u32()?)))?),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

