// This file is @generated by bebopc-gen-rust. DO NOT EDIT.
// source: /Users/mayfield/vendor/bebop-next/plugins/rust/integration-tests/schemas/test_types.bop
// bebopc 2026.0.0-alpha.2
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE

#![allow(warnings)]
#![no_implicit_prelude]

extern crate alloc;
extern crate bebop_runtime;
extern crate core;
use alloc::vec;
use bebop_runtime::serde;
use bebop_runtime::wire_size as wire;
use bebop_runtime::{
  bf16, f16, BebopDecode, BebopDuration, BebopEncode, BebopFlags, BebopReader, BebopTimestamp,
  BebopWriter, DecodeError,
};
use core::convert::Into as _;
use core::iter::IntoIterator as _;
use core::iter::Iterator as _;

// @@bebop_insertion_point(imports)

/// Simple enum with uint8 base type.
#[repr(u8)]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Color {
  Unknown = 0,
  Red = 1,
  Green = 2,
  Blue = 3,
}

impl ::core::convert::TryFrom<u8> for Color {
  type Error = DecodeError;
  fn try_from(value: u8) -> ::core::result::Result<Self, DecodeError> {
    match value {
      0 => ::core::result::Result::Ok(Self::Unknown),
      1 => ::core::result::Result::Ok(Self::Red),
      2 => ::core::result::Result::Ok(Self::Green),
      3 => ::core::result::Result::Ok(Self::Blue),
      _ => ::core::result::Result::Err(DecodeError::InvalidEnum {
        type_name: "Color",
        value: value as u64,
      }),
    }
  }
}

impl ::core::convert::From<Color> for u8 {
  fn from(value: Color) -> u8 {
    value as u8
  }
}

impl Color {
  pub const FIXED_ENCODED_SIZE: usize = 1;
  // @@bebop_insertion_point(enum_scope:Color)
}

impl BebopEncode for Color {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Color)
    writer.write_byte(*self as u8);
    // @@bebop_insertion_point(encode_end:Color)
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Color {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Color)
    let value = reader.read_byte()?;
    // @@bebop_insertion_point(decode_end:Color)
    ::core::convert::TryFrom::try_from(value)
  }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Permissions(pub u8);

#[allow(non_upper_case_globals)]
impl Permissions {
  pub const FIXED_ENCODED_SIZE: usize = 1;
  pub const NONE: Self = Self(0);
  pub const READ: Self = Self(1);
  pub const WRITE: Self = Self(2);
  pub const EXECUTE: Self = Self(4);
  pub const ALL: Self = Self(7);
  // @@bebop_insertion_point(enum_scope:Permissions)
}

impl BebopFlags for Permissions {
  type Bits = u8;
  const ALL_BITS: Self::Bits = 7;
  fn bits(self) -> Self::Bits {
    self.0
  }
  fn from_bits_retain(bits: Self::Bits) -> Self {
    Self(bits)
  }
}

impl ::core::ops::BitOr for Permissions {
  type Output = Self;
  fn bitor(self, rhs: Self) -> Self {
    Self(self.0 | rhs.0)
  }
}
impl ::core::ops::BitOrAssign for Permissions {
  fn bitor_assign(&mut self, rhs: Self) {
    self.0 |= rhs.0;
  }
}
impl ::core::ops::BitAnd for Permissions {
  type Output = Self;
  fn bitand(self, rhs: Self) -> Self {
    Self(self.0 & rhs.0)
  }
}
impl ::core::ops::BitAndAssign for Permissions {
  fn bitand_assign(&mut self, rhs: Self) {
    self.0 &= rhs.0;
  }
}
impl ::core::ops::BitXor for Permissions {
  type Output = Self;
  fn bitxor(self, rhs: Self) -> Self {
    Self(self.0 ^ rhs.0)
  }
}
impl ::core::ops::BitXorAssign for Permissions {
  fn bitxor_assign(&mut self, rhs: Self) {
    self.0 ^= rhs.0;
  }
}
impl ::core::ops::Not for Permissions {
  type Output = Self;
  fn not(self) -> Self {
    Self(!self.0)
  }
}
impl ::core::ops::Sub for Permissions {
  type Output = Self;
  fn sub(self, rhs: Self) -> Self {
    Self(self.0 & !rhs.0)
  }
}

impl<'buf> BebopDecode<'buf> for Permissions {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    let bits = reader.read_byte()?;
    Self::from_bits(bits).ok_or(DecodeError::InvalidFlags {
      type_name: "Permissions",
      bits: bits as u64,
    })
  }
}

/// Constants used to validate Rust const generation.
pub const P_CASE: u8 = 18u8;

pub const EXAMPLE_CONST_INT32: i32 = -123i32;

pub const EXAMPLE_CONST_UINT64: u64 = 1254130450431u64;

pub const EXAMPLE_CONST_FLOAT64: f64 = 123456780000.0f64;

pub const EXAMPLE_CONST_INF: f64 = f64::INFINITY;

pub const EXAMPLE_CONST_NEG_INF: f64 = f64::NEG_INFINITY;

pub const EXAMPLE_CONST_NAN: f64 = f64::NAN;

pub const EXAMPLE_CONST_FALSE: bool = false;

pub const EXAMPLE_CONST_TRUE: bool = true;

pub const HTTP_STATUS_OK: u32 = 200u32;

pub const FEATURE_FLAG_ENABLED: bool = true;

pub const EXAMPLE_CONST_STRING: &str = "hello \"world\"\nwith newlines";

pub const EXAMPLE_CONST_GUID: ::bebop_runtime::Uuid = ::bebop_runtime::Uuid::from_bytes([
  0xE2, 0x15, 0xA9, 0x46, 0xB2, 0x6F, 0x45, 0x67, 0xA2, 0x76, 0x13, 0x13, 0x6F, 0x0A, 0x17, 0x08,
]);

pub const EXAMPLE_CONST_F16: f16 = f16::from_f64_const(1.5f64);

pub const EXAMPLE_CONST_BF16: bf16 = bf16::from_f64_const(1.5f64);

pub const EXAMPLE_CONST_F16_INF: f16 = f16::INFINITY;

pub const EXAMPLE_CONST_BF16_NEG_INF: bf16 = bf16::NEG_INFINITY;

pub const EXAMPLE_CONST_F16_NAN: f16 = f16::NAN;

pub const EXAMPLE_CONST_BF16_NAN: bf16 = bf16::NAN;

pub const EXAMPLE_CONST_F16_FROM_INT: f16 = f16::from_f64_const(1f64);

pub const EXAMPLE_CONST_BF16_FROM_INT: bf16 = bf16::from_f64_const(2f64);

/// Fixed-size struct (all scalar fields).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Point {
  pub x: f32,
  pub y: f32,
}

impl Point {
  pub const FIXED_ENCODED_SIZE: usize =
    ::core::mem::size_of::<f32>() + ::core::mem::size_of::<f32>();

  pub fn new(x: f32, y: f32) -> Self {
    Self { x, y }
  }
}

impl BebopEncode for Point {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Point)
    writer.write_f32(self.x);
    writer.write_f32(self.y);
    // @@bebop_insertion_point(encode_end:Point)
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Point {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Point)
    let x = reader.read_f32()?;
    let y = reader.read_f32()?;
    // @@bebop_insertion_point(decode_end:Point)
    ::core::result::Result::Ok(Point { x, y })
  }
}

impl Point {
  // @@bebop_insertion_point(struct_scope:Point)
}

/// Fixed-size struct referencing another struct and an enum.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Pixel {
  pub position: Point,
  pub color: Color,
  pub alpha: u8,
}

impl Pixel {
  pub const FIXED_ENCODED_SIZE: usize =
    Point::FIXED_ENCODED_SIZE + Color::FIXED_ENCODED_SIZE + ::core::mem::size_of::<u8>();

  pub fn new(position: Point, color: Color, alpha: u8) -> Self {
    Self {
      position,
      color,
      alpha,
    }
  }
}

impl BebopEncode for Pixel {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Pixel)
    self.position.encode(writer);
    self.color.encode(writer);
    writer.write_byte(self.alpha);
    // @@bebop_insertion_point(encode_end:Pixel)
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Pixel {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Pixel)
    let position = Point::decode(reader)?;
    let color = Color::decode(reader)?;
    let alpha = reader.read_byte()?;
    // @@bebop_insertion_point(decode_end:Pixel)
    ::core::result::Result::Ok(Pixel {
      position,
      color,
      alpha,
    })
  }
}

impl Pixel {
  // @@bebop_insertion_point(struct_scope:Pixel)
}

/// Variable-size struct with a string field (needs lifetime / Cow).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct Person<'buf> {
  pub name: alloc::borrow::Cow<'buf, str>,
  pub age: u32,
}

pub type PersonOwned = Person<'static>;

impl<'buf> Person<'buf> {
  pub fn new(name: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>, age: u32) -> Self {
    let name = ::core::convert::Into::into(name);
    Self { name, age }
  }
}

impl<'buf> Person<'buf> {
  pub fn into_owned(self) -> PersonOwned {
    Person {
      name: alloc::borrow::Cow::Owned(self.name.into_owned()),
      age: self.age,
    }
  }
}

impl<'buf> BebopEncode for Person<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Person)
    writer.write_string(&self.name);
    writer.write_u32(self.age);
    // @@bebop_insertion_point(encode_end:Person)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.name.len());
    size += ::core::mem::size_of::<u32>();
    size
  }
}

impl<'buf> BebopDecode<'buf> for Person<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Person)
    let name = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    let age = reader.read_u32()?;
    // @@bebop_insertion_point(decode_end:Person)
    ::core::result::Result::Ok(Person { name, age })
  }
}

impl<'buf> Person<'buf> {
  // @@bebop_insertion_point(struct_scope:Person)
}

/// Variable-size struct with a byte array field (needs lifetime / Cow).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct BinaryPayload<'buf> {
  pub tag: u32,
  pub data: ::bebop_runtime::BebopBytes<'buf>,
}

pub type BinaryPayloadOwned = BinaryPayload<'static>;

impl<'buf> BinaryPayload<'buf> {
  pub fn new(
    tag: u32,
    data: impl ::core::convert::Into<::bebop_runtime::BebopBytes<'buf>>,
  ) -> Self {
    let data = ::core::convert::Into::into(data);
    Self { tag, data }
  }
}

impl<'buf> BinaryPayload<'buf> {
  pub fn into_owned(self) -> BinaryPayloadOwned {
    BinaryPayload {
      tag: self.tag,
      data: self.data.into_owned(),
    }
  }
}

impl<'buf> BebopEncode for BinaryPayload<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:BinaryPayload)
    writer.write_u32(self.tag);
    writer.write_byte_array(&self.data);
    // @@bebop_insertion_point(encode_end:BinaryPayload)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += ::core::mem::size_of::<u32>();
    size += wire::byte_array_size(self.data.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for BinaryPayload<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:BinaryPayload)
    let tag = reader.read_u32()?;
    let data = ::bebop_runtime::BebopBytes::borrowed(reader.read_byte_slice()?);
    // @@bebop_insertion_point(decode_end:BinaryPayload)
    ::core::result::Result::Ok(BinaryPayload { tag, data })
  }
}

impl<'buf> BinaryPayload<'buf> {
  // @@bebop_insertion_point(struct_scope:BinaryPayload)
}

/// Message with various field types: scalars, strings, arrays, maps.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq)]
pub struct UserProfile<'buf> {
  pub display_name: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  pub email: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  pub age: ::core::option::Option<u32>,
  pub active: ::core::option::Option<bool>,
  pub tags: ::core::option::Option<alloc::vec::Vec<alloc::borrow::Cow<'buf, str>>>,
  pub metadata: ::core::option::Option<
    ::bebop_runtime::HashMap<alloc::borrow::Cow<'buf, str>, alloc::borrow::Cow<'buf, str>>,
  >,
  pub permissions: ::core::option::Option<Permissions>,
}

pub type UserProfileOwned = UserProfile<'static>;

impl<'buf> UserProfile<'buf> {
  pub fn into_owned(self) -> UserProfileOwned {
    UserProfile {
      display_name: self
        .display_name
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      email: self
        .email
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      age: self.age,
      active: self.active,
      tags: self.tags.map(|v| {
        v.into_iter()
          .map(|_e| alloc::borrow::Cow::Owned(_e.into_owned()))
          .collect()
      }),
      metadata: self.metadata.map(|v| {
        v.into_iter()
          .map(|(_k, _v)| {
            (
              alloc::borrow::Cow::Owned(_k.into_owned()),
              alloc::borrow::Cow::Owned(_v.into_owned()),
            )
          })
          .collect()
      }),
      permissions: self.permissions,
    }
  }
}

impl<'buf> BebopEncode for UserProfile<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:UserProfile)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.display_name {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(ref v) = self.email {
      writer.write_tag(2);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(v) = self.age {
      writer.write_tag(3);
      writer.write_u32(v);
    }
    if let ::core::option::Option::Some(v) = self.active {
      writer.write_tag(4);
      writer.write_bool(v);
    }
    if let ::core::option::Option::Some(ref v) = self.tags {
      writer.write_tag(5);
      writer.write_array(&v, |_w, _el| _w.write_string(_el));
    }
    if let ::core::option::Option::Some(ref v) = self.metadata {
      writer.write_tag(6);
      writer.write_map(&v, |_w, _k, _v| {
        _w.write_string(&_k);
        _w.write_string(&_v);
      });
    }
    if let ::core::option::Option::Some(ref v) = self.permissions {
      writer.write_tag(7);
      v.encode(writer);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:UserProfile)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.display_name {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(ref v) = self.email {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(v) = self.age {
      size += wire::tagged_size(::core::mem::size_of::<u32>());
    }
    if let ::core::option::Option::Some(v) = self.active {
      size += wire::tagged_size(::core::mem::size_of::<bool>());
    }
    if let ::core::option::Option::Some(ref v) = self.tags {
      size += wire::tagged_size(wire::array_size(v, |_el| wire::string_size(_el.len())));
    }
    if let ::core::option::Option::Some(ref v) = self.metadata {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| {
        wire::string_size(_k.len()) + wire::string_size(_v.len())
      }));
    }
    if let ::core::option::Option::Some(ref v) = self.permissions {
      size += wire::tagged_size(v.encoded_size());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for UserProfile<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:UserProfile)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.display_name =
            ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        2 => {
          msg.email = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        3 => msg.age = ::core::option::Option::Some(reader.read_u32()?),
        4 => msg.active = ::core::option::Option::Some(reader.read_bool()?),
        5 => {
          msg.tags = ::core::option::Option::Some(reader.read_array(|_r| {
            ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))
          })?)
        }
        6 => {
          msg.metadata = ::core::option::Option::Some(reader.read_map(|_r| {
            ::core::result::Result::Ok((
              ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
              ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
            ))
          })?)
        }
        7 => msg.permissions = ::core::option::Option::Some(Permissions::decode(reader)?),
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "UserProfile",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:UserProfile)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> UserProfile<'buf> {
  // @@bebop_insertion_point(message_scope:UserProfile)
}

/// Message referencing fixed-size and enum defined types.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq)]
pub struct DrawCommand<'buf> {
  pub target: ::core::option::Option<Point>,
  pub color: ::core::option::Option<Color>,
  pub label: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  pub thickness: ::core::option::Option<f32>,
}

pub type DrawCommandOwned = DrawCommand<'static>;

impl<'buf> DrawCommand<'buf> {
  pub fn into_owned(self) -> DrawCommandOwned {
    DrawCommand {
      target: self.target,
      color: self.color,
      label: self
        .label
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      thickness: self.thickness,
    }
  }
}

impl<'buf> BebopEncode for DrawCommand<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:DrawCommand)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.target {
      writer.write_tag(1);
      v.encode(writer);
    }
    if let ::core::option::Option::Some(ref v) = self.color {
      writer.write_tag(2);
      v.encode(writer);
    }
    if let ::core::option::Option::Some(ref v) = self.label {
      writer.write_tag(3);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(v) = self.thickness {
      writer.write_tag(4);
      writer.write_f32(v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:DrawCommand)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.target {
      size += wire::tagged_size(v.encoded_size());
    }
    if let ::core::option::Option::Some(ref v) = self.color {
      size += wire::tagged_size(v.encoded_size());
    }
    if let ::core::option::Option::Some(ref v) = self.label {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(v) = self.thickness {
      size += wire::tagged_size(::core::mem::size_of::<f32>());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for DrawCommand<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:DrawCommand)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => msg.target = ::core::option::Option::Some(Point::decode(reader)?),
        2 => msg.color = ::core::option::Option::Some(Color::decode(reader)?),
        3 => {
          msg.label = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        4 => msg.thickness = ::core::option::Option::Some(reader.read_f32()?),
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "DrawCommand",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:DrawCommand)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> DrawCommand<'buf> {
  // @@bebop_insertion_point(message_scope:DrawCommand)
}

/// Struct used as a union branch (variable-size due to string field).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct TextLabel<'buf> {
  pub position: Point,
  pub text: alloc::borrow::Cow<'buf, str>,
}

pub type TextLabelOwned = TextLabel<'static>;

impl<'buf> TextLabel<'buf> {
  pub fn new(
    position: Point,
    text: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
  ) -> Self {
    let text = ::core::convert::Into::into(text);
    Self { position, text }
  }
}

impl<'buf> TextLabel<'buf> {
  pub fn into_owned(self) -> TextLabelOwned {
    TextLabel {
      position: self.position,
      text: alloc::borrow::Cow::Owned(self.text.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for TextLabel<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:TextLabel)
    self.position.encode(writer);
    writer.write_string(&self.text);
    // @@bebop_insertion_point(encode_end:TextLabel)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += self.position.encoded_size();
    size += wire::string_size(self.text.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for TextLabel<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:TextLabel)
    let position = Point::decode(reader)?;
    let text = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    // @@bebop_insertion_point(decode_end:TextLabel)
    ::core::result::Result::Ok(TextLabel { position, text })
  }
}

impl<'buf> TextLabel<'buf> {
  // @@bebop_insertion_point(struct_scope:TextLabel)
}

#[derive(serde::Serialize, serde::Deserialize)]
#[serde(tag = "type", content = "value")]
#[derive(Debug, Clone, PartialEq)]
pub enum Shape<'buf> {
  Point(Point),
  Pixel(Pixel),
  Label(TextLabel<'buf>),
  #[serde(skip)]
  Unknown(u8, alloc::borrow::Cow<'buf, [u8]>),
}

pub type ShapeOwned = Shape<'static>;

impl<'buf> Shape<'buf> {
  pub fn into_owned(self) -> ShapeOwned {
    match self {
      Self::Point(inner) => Shape::Point(inner),
      Self::Pixel(inner) => Shape::Pixel(inner),
      Self::Label(inner) => Shape::Label(inner.into_owned()),
      Self::Unknown(disc, data) => {
        Shape::Unknown(disc, alloc::borrow::Cow::Owned(data.into_owned()))
      }
    }
  }
}

impl<'buf> BebopEncode for Shape<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Shape)
    let pos = writer.reserve_message_length();
    match self {
      Self::Point(inner) => {
        writer.write_byte(1);
        inner.encode(writer);
      }
      Self::Pixel(inner) => {
        writer.write_byte(2);
        inner.encode(writer);
      }
      Self::Label(inner) => {
        writer.write_byte(3);
        inner.encode(writer);
      }
      // @@bebop_insertion_point(encode_switch:Shape)
      Self::Unknown(disc, data) => {
        writer.write_byte(*disc);
        writer.write_raw(data);
      }
    }
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:Shape)
  }

  fn encoded_size(&self) -> usize {
    wire::WIRE_LEN_PREFIX_SIZE
      + match self {
        Self::Point(inner) => wire::tagged_size(inner.encoded_size()),
        Self::Pixel(inner) => wire::tagged_size(inner.encoded_size()),
        Self::Label(inner) => wire::tagged_size(inner.encoded_size()),
        Self::Unknown(_, data) => wire::tagged_size(data.len()),
      }
  }
}

impl<'buf> BebopDecode<'buf> for Shape<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Shape)
    let length = reader.read_message_length()? as usize;
    let start = reader.position();
    let discriminator = reader.read_byte()?;
    let value = match discriminator {
      1 => ::core::result::Result::Ok(Self::Point(Point::decode(reader)?)),
      2 => ::core::result::Result::Ok(Self::Pixel(Pixel::decode(reader)?)),
      3 => ::core::result::Result::Ok(Self::Label(TextLabel::decode(reader)?)),
      // @@bebop_insertion_point(decode_switch:Shape)
      _ => {
        let remaining = length - (reader.position() - start);
        let data = reader.read_raw_bytes(remaining)?;
        ::core::result::Result::Ok(Self::Unknown(
          discriminator,
          alloc::borrow::Cow::Borrowed(data),
        ))
      }
    };
    // @@bebop_insertion_point(decode_end:Shape)
    value
  }
}

impl<'buf> Shape<'buf> {
  // @@bebop_insertion_point(union_scope:Shape)
}

/// Strict union: unknown discriminators are rejected with DecodeError.
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(tag = "type", content = "value")]
#[derive(Debug, Clone, PartialEq)]
pub enum StrictShape {
  Point(Point),
  Pixel(Pixel),
}

impl BebopEncode for StrictShape {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:StrictShape)
    let pos = writer.reserve_message_length();
    match self {
      Self::Point(inner) => {
        writer.write_byte(1);
        inner.encode(writer);
      }
      Self::Pixel(inner) => {
        writer.write_byte(2);
        inner.encode(writer);
      }
    }
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:StrictShape)
  }

  fn encoded_size(&self) -> usize {
    wire::WIRE_LEN_PREFIX_SIZE
      + match self {
        Self::Point(inner) => wire::tagged_size(inner.encoded_size()),
        Self::Pixel(inner) => wire::tagged_size(inner.encoded_size()),
      }
  }
}

impl<'buf> BebopDecode<'buf> for StrictShape {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:StrictShape)
    let length = reader.read_message_length()? as usize;
    let start = reader.position();
    let discriminator = reader.read_byte()?;
    let value = match discriminator {
      1 => ::core::result::Result::Ok(Self::Point(Point::decode(reader)?)),
      2 => ::core::result::Result::Ok(Self::Pixel(Pixel::decode(reader)?)),
      _ => ::core::result::Result::Err(DecodeError::InvalidUnion {
        type_name: "StrictShape",
        discriminator,
      }),
    };
    // @@bebop_insertion_point(decode_end:StrictShape)
    value
  }
}

impl StrictShape {
  // @@bebop_insertion_point(union_scope:StrictShape)
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Priority {
  Unspecified,
  Low,
  Medium,
  High,
  /// A discriminator value not recognized by this version of the schema.
  Unknown(u8),
}

impl Priority {
  pub const FIXED_ENCODED_SIZE: usize = 1;

  /// Returns the raw discriminator value.
  pub fn discriminator(self) -> u8 {
    match self {
      Self::Unspecified => 0,
      Self::Low => 1,
      Self::Medium => 2,
      Self::High => 3,
      Self::Unknown(v) => v,
    }
  }

  /// Returns `true` if this value matches a known variant.
  pub fn is_known(&self) -> bool {
    !::core::matches!(self, Self::Unknown(_))
  }
  // @@bebop_insertion_point(enum_scope:Priority)
}

impl ::core::convert::From<u8> for Priority {
  fn from(value: u8) -> Self {
    match value {
      0 => Self::Unspecified,
      1 => Self::Low,
      2 => Self::Medium,
      3 => Self::High,
      v => Self::Unknown(v),
    }
  }
}

impl ::core::convert::From<Priority> for u8 {
  fn from(value: Priority) -> u8 {
    value.discriminator()
  }
}

impl BebopEncode for Priority {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Priority)
    writer.write_byte(self.discriminator());
    // @@bebop_insertion_point(encode_end:Priority)
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Priority {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Priority)
    let value = reader.read_byte()?;
    // @@bebop_insertion_point(decode_end:Priority)
    ::core::result::Result::Ok(<Self as ::core::convert::From<_>>::from(value))
  }
}

/// Strict message: unknown field tags are rejected with DecodeError.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct StrictConfig<'buf> {
  pub name: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  pub value: ::core::option::Option<u32>,
}

pub type StrictConfigOwned = StrictConfig<'static>;

impl<'buf> StrictConfig<'buf> {
  pub fn into_owned(self) -> StrictConfigOwned {
    StrictConfig {
      name: self.name.map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      value: self.value,
    }
  }
}

impl<'buf> BebopEncode for StrictConfig<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:StrictConfig)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.name {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(v) = self.value {
      writer.write_tag(2);
      writer.write_u32(v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:StrictConfig)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.name {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(v) = self.value {
      size += wire::tagged_size(::core::mem::size_of::<u32>());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for StrictConfig<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:StrictConfig)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.name = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        2 => msg.value = ::core::option::Option::Some(reader.read_u32()?),
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "StrictConfig",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:StrictConfig)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> StrictConfig<'buf> {
  // @@bebop_insertion_point(message_scope:StrictConfig)
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct FlexConfig<'buf> {
  pub name: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  pub value: ::core::option::Option<u32>,
}

pub type FlexConfigOwned = FlexConfig<'static>;

impl<'buf> FlexConfig<'buf> {
  pub fn into_owned(self) -> FlexConfigOwned {
    FlexConfig {
      name: self.name.map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      value: self.value,
    }
  }
}

impl<'buf> BebopEncode for FlexConfig<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:FlexConfig)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.name {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(v) = self.value {
      writer.write_tag(2);
      writer.write_u32(v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:FlexConfig)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.name {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(v) = self.value {
      size += wire::tagged_size(::core::mem::size_of::<u32>());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for FlexConfig<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:FlexConfig)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.name = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        2 => msg.value = ::core::option::Option::Some(reader.read_u32()?),
        _ => {
          reader.skip(end - reader.position())?;
        }
      }
    }
    // @@bebop_insertion_point(decode_end:FlexConfig)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> FlexConfig<'buf> {
  // @@bebop_insertion_point(message_scope:FlexConfig)
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct FlexPermissions(pub u8);

#[allow(non_upper_case_globals)]
impl FlexPermissions {
  pub const FIXED_ENCODED_SIZE: usize = 1;
  pub const NONE: Self = Self(0);
  pub const READ: Self = Self(1);
  pub const WRITE: Self = Self(2);
  // @@bebop_insertion_point(enum_scope:FlexPermissions)
}

impl BebopFlags for FlexPermissions {
  type Bits = u8;
  const ALL_BITS: Self::Bits = 3;
  fn bits(self) -> Self::Bits {
    self.0
  }
  fn from_bits_retain(bits: Self::Bits) -> Self {
    Self(bits)
  }
}

impl ::core::ops::BitOr for FlexPermissions {
  type Output = Self;
  fn bitor(self, rhs: Self) -> Self {
    Self(self.0 | rhs.0)
  }
}
impl ::core::ops::BitOrAssign for FlexPermissions {
  fn bitor_assign(&mut self, rhs: Self) {
    self.0 |= rhs.0;
  }
}
impl ::core::ops::BitAnd for FlexPermissions {
  type Output = Self;
  fn bitand(self, rhs: Self) -> Self {
    Self(self.0 & rhs.0)
  }
}
impl ::core::ops::BitAndAssign for FlexPermissions {
  fn bitand_assign(&mut self, rhs: Self) {
    self.0 &= rhs.0;
  }
}
impl ::core::ops::BitXor for FlexPermissions {
  type Output = Self;
  fn bitxor(self, rhs: Self) -> Self {
    Self(self.0 ^ rhs.0)
  }
}
impl ::core::ops::BitXorAssign for FlexPermissions {
  fn bitxor_assign(&mut self, rhs: Self) {
    self.0 ^= rhs.0;
  }
}
impl ::core::ops::Not for FlexPermissions {
  type Output = Self;
  fn not(self) -> Self {
    Self(!self.0)
  }
}
impl ::core::ops::Sub for FlexPermissions {
  type Output = Self;
  fn sub(self, rhs: Self) -> Self {
    Self(self.0 & !rhs.0)
  }
}

impl<'buf> BebopDecode<'buf> for FlexPermissions {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    let bits = reader.read_byte()?;
    ::core::result::Result::Ok(Self::from_bits_retain(bits))
  }
}

/// Fixed-array struct (compile-time known element count).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct Matrix2x2 {
  pub values: [f32; 4],
}

impl Matrix2x2 {
  pub const FIXED_ENCODED_SIZE: usize = ::core::mem::size_of::<f32>() * 4;

  pub fn new(values: [f32; 4]) -> Self {
    Self { values }
  }
}

impl BebopEncode for Matrix2x2 {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Matrix2x2)
    writer.write_fixed_array::<f32, 4>(&self.values);
    // @@bebop_insertion_point(encode_end:Matrix2x2)
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Matrix2x2 {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Matrix2x2)
    let values = reader.read_fixed_array::<f32, 4>()?;
    // @@bebop_insertion_point(decode_end:Matrix2x2)
    ::core::result::Result::Ok(Matrix2x2 { values })
  }
}

impl Matrix2x2 {
  // @@bebop_insertion_point(struct_scope:Matrix2x2)
}

/// Fixed-size and variable-size half-precision scalar coverage.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct HalfPrecisionScalars {
  pub f16_val: f16,
  pub bf16_val: bf16,
}

impl HalfPrecisionScalars {
  pub const FIXED_ENCODED_SIZE: usize =
    ::core::mem::size_of::<f16>() + ::core::mem::size_of::<bf16>();

  pub fn new(f16_val: f16, bf16_val: bf16) -> Self {
    Self { f16_val, bf16_val }
  }
}

impl BebopEncode for HalfPrecisionScalars {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:HalfPrecisionScalars)
    writer.write_f16(self.f16_val);
    writer.write_bf16(self.bf16_val);
    // @@bebop_insertion_point(encode_end:HalfPrecisionScalars)
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for HalfPrecisionScalars {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:HalfPrecisionScalars)
    let f16_val = reader.read_f16()?;
    let bf16_val = reader.read_bf16()?;
    // @@bebop_insertion_point(decode_end:HalfPrecisionScalars)
    ::core::result::Result::Ok(HalfPrecisionScalars { f16_val, bf16_val })
  }
}

impl HalfPrecisionScalars {
  // @@bebop_insertion_point(struct_scope:HalfPrecisionScalars)
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq)]
pub struct HalfPrecisionArrays<'buf> {
  pub f16_dynamic: alloc::borrow::Cow<'buf, [f16]>,
  pub bf16_dynamic: alloc::borrow::Cow<'buf, [bf16]>,
  pub f16_fixed: [f16; 4],
  pub bf16_fixed: [bf16; 4],
}

pub type HalfPrecisionArraysOwned = HalfPrecisionArrays<'static>;

impl<'buf> HalfPrecisionArrays<'buf> {
  pub fn new(
    f16_dynamic: impl ::core::convert::Into<alloc::borrow::Cow<'buf, [f16]>>,
    bf16_dynamic: impl ::core::convert::Into<alloc::borrow::Cow<'buf, [bf16]>>,
    f16_fixed: [f16; 4],
    bf16_fixed: [bf16; 4],
  ) -> Self {
    let f16_dynamic = ::core::convert::Into::into(f16_dynamic);
    let bf16_dynamic = ::core::convert::Into::into(bf16_dynamic);
    Self {
      f16_dynamic,
      bf16_dynamic,
      f16_fixed,
      bf16_fixed,
    }
  }
}

impl<'buf> HalfPrecisionArrays<'buf> {
  pub fn into_owned(self) -> HalfPrecisionArraysOwned {
    HalfPrecisionArrays {
      f16_dynamic: alloc::borrow::Cow::Owned(self.f16_dynamic.into_owned()),
      bf16_dynamic: alloc::borrow::Cow::Owned(self.bf16_dynamic.into_owned()),
      f16_fixed: self.f16_fixed,
      bf16_fixed: self.bf16_fixed,
    }
  }
}

impl<'buf> BebopEncode for HalfPrecisionArrays<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:HalfPrecisionArrays)
    writer.write_scalar_array::<f16>(&self.f16_dynamic);
    writer.write_scalar_array::<bf16>(&self.bf16_dynamic);
    writer.write_fixed_array::<f16, 4>(&self.f16_fixed);
    writer.write_fixed_array::<bf16, 4>(&self.bf16_fixed);
    // @@bebop_insertion_point(encode_end:HalfPrecisionArrays)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::array_size(&self.f16_dynamic, |_el| (::core::mem::size_of::<f16>()));
    size += wire::array_size(&self.bf16_dynamic, |_el| (::core::mem::size_of::<bf16>()));
    size += 4usize * (::core::mem::size_of::<f16>());
    size += 4usize * (::core::mem::size_of::<bf16>());
    size
  }
}

impl<'buf> BebopDecode<'buf> for HalfPrecisionArrays<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:HalfPrecisionArrays)
    let f16_dynamic = reader.read_scalar_array::<f16>()?;
    let bf16_dynamic = reader.read_scalar_array::<bf16>()?;
    let f16_fixed = reader.read_fixed_array::<f16, 4>()?;
    let bf16_fixed = reader.read_fixed_array::<bf16, 4>()?;
    // @@bebop_insertion_point(decode_end:HalfPrecisionArrays)
    ::core::result::Result::Ok(HalfPrecisionArrays {
      f16_dynamic,
      bf16_dynamic,
      f16_fixed,
      bf16_fixed,
    })
  }
}

impl<'buf> HalfPrecisionArrays<'buf> {
  // @@bebop_insertion_point(struct_scope:HalfPrecisionArrays)
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq)]
pub struct HalfPrecisionMessage<'buf> {
  pub f16_val: ::core::option::Option<f16>,
  pub bf16_val: ::core::option::Option<bf16>,
  pub f16_arr: ::core::option::Option<alloc::borrow::Cow<'buf, [f16]>>,
  pub bf16_arr: ::core::option::Option<alloc::borrow::Cow<'buf, [bf16]>>,
}

pub type HalfPrecisionMessageOwned = HalfPrecisionMessage<'static>;

impl<'buf> HalfPrecisionMessage<'buf> {
  pub fn into_owned(self) -> HalfPrecisionMessageOwned {
    HalfPrecisionMessage {
      f16_val: self.f16_val,
      bf16_val: self.bf16_val,
      f16_arr: self
        .f16_arr
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      bf16_arr: self
        .bf16_arr
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for HalfPrecisionMessage<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:HalfPrecisionMessage)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(v) = self.f16_val {
      writer.write_tag(1);
      writer.write_f16(v);
    }
    if let ::core::option::Option::Some(v) = self.bf16_val {
      writer.write_tag(2);
      writer.write_bf16(v);
    }
    if let ::core::option::Option::Some(ref v) = self.f16_arr {
      writer.write_tag(3);
      writer.write_scalar_array::<f16>(&v);
    }
    if let ::core::option::Option::Some(ref v) = self.bf16_arr {
      writer.write_tag(4);
      writer.write_scalar_array::<bf16>(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:HalfPrecisionMessage)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(v) = self.f16_val {
      size += wire::tagged_size(::core::mem::size_of::<f16>());
    }
    if let ::core::option::Option::Some(v) = self.bf16_val {
      size += wire::tagged_size(::core::mem::size_of::<bf16>());
    }
    if let ::core::option::Option::Some(ref v) = self.f16_arr {
      size += wire::tagged_size(wire::array_size(v, |_el| (::core::mem::size_of::<f16>())));
    }
    if let ::core::option::Option::Some(ref v) = self.bf16_arr {
      size += wire::tagged_size(wire::array_size(v, |_el| (::core::mem::size_of::<bf16>())));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for HalfPrecisionMessage<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:HalfPrecisionMessage)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => msg.f16_val = ::core::option::Option::Some(reader.read_f16()?),
        2 => msg.bf16_val = ::core::option::Option::Some(reader.read_bf16()?),
        3 => msg.f16_arr = ::core::option::Option::Some(reader.read_scalar_array::<f16>()?),
        4 => msg.bf16_arr = ::core::option::Option::Some(reader.read_scalar_array::<bf16>()?),
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "HalfPrecisionMessage",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:HalfPrecisionMessage)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> HalfPrecisionMessage<'buf> {
  // @@bebop_insertion_point(message_scope:HalfPrecisionMessage)
}

/// Struct with multiple string fields (all need Cow).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct Address<'buf> {
  pub street: alloc::borrow::Cow<'buf, str>,
  pub city: alloc::borrow::Cow<'buf, str>,
  pub country: alloc::borrow::Cow<'buf, str>,
  pub zip_code: alloc::borrow::Cow<'buf, str>,
}

pub type AddressOwned = Address<'static>;

impl<'buf> Address<'buf> {
  pub fn new(
    street: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
    city: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
    country: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
    zip_code: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
  ) -> Self {
    let street = ::core::convert::Into::into(street);
    let city = ::core::convert::Into::into(city);
    let country = ::core::convert::Into::into(country);
    let zip_code = ::core::convert::Into::into(zip_code);
    Self {
      street,
      city,
      country,
      zip_code,
    }
  }
}

impl<'buf> Address<'buf> {
  pub fn into_owned(self) -> AddressOwned {
    Address {
      street: alloc::borrow::Cow::Owned(self.street.into_owned()),
      city: alloc::borrow::Cow::Owned(self.city.into_owned()),
      country: alloc::borrow::Cow::Owned(self.country.into_owned()),
      zip_code: alloc::borrow::Cow::Owned(self.zip_code.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for Address<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Address)
    writer.write_string(&self.street);
    writer.write_string(&self.city);
    writer.write_string(&self.country);
    writer.write_string(&self.zip_code);
    // @@bebop_insertion_point(encode_end:Address)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.street.len());
    size += wire::string_size(self.city.len());
    size += wire::string_size(self.country.len());
    size += wire::string_size(self.zip_code.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for Address<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Address)
    let street = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    let city = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    let country = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    let zip_code = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    // @@bebop_insertion_point(decode_end:Address)
    ::core::result::Result::Ok(Address {
      street,
      city,
      country,
      zip_code,
    })
  }
}

impl<'buf> Address<'buf> {
  // @@bebop_insertion_point(struct_scope:Address)
}

/// Message with array-of-defined-type and nested references.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq)]
pub struct Scene<'buf> {
  pub shapes: ::core::option::Option<alloc::vec::Vec<Shape<'buf>>>,
  pub background: ::core::option::Option<Color>,
  pub title: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
}

pub type SceneOwned = Scene<'static>;

impl<'buf> Scene<'buf> {
  pub fn into_owned(self) -> SceneOwned {
    Scene {
      shapes: self
        .shapes
        .map(|v| v.into_iter().map(|_e| _e.into_owned()).collect()),
      background: self.background,
      title: self
        .title
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for Scene<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Scene)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.shapes {
      writer.write_tag(1);
      writer.write_array(&v, |_w, _el| _el.encode(_w));
    }
    if let ::core::option::Option::Some(ref v) = self.background {
      writer.write_tag(2);
      v.encode(writer);
    }
    if let ::core::option::Option::Some(ref v) = self.title {
      writer.write_tag(3);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:Scene)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.shapes {
      size += wire::tagged_size(wire::array_size(v, |_el| _el.encoded_size()));
    }
    if let ::core::option::Option::Some(ref v) = self.background {
      size += wire::tagged_size(v.encoded_size());
    }
    if let ::core::option::Option::Some(ref v) = self.title {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for Scene<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Scene)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => msg.shapes = ::core::option::Option::Some(reader.read_array(|_r| Shape::decode(_r))?),
        2 => msg.background = ::core::option::Option::Some(Color::decode(reader)?),
        3 => {
          msg.title = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "Scene",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:Scene)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> Scene<'buf> {
  // @@bebop_insertion_point(message_scope:Scene)
}

/// Message with map[string, defined-type] value.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq)]
pub struct Inventory<'buf> {
  pub items: ::core::option::Option<::bebop_runtime::HashMap<alloc::borrow::Cow<'buf, str>, u32>>,
  pub label: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
}

pub type InventoryOwned = Inventory<'static>;

impl<'buf> Inventory<'buf> {
  pub fn into_owned(self) -> InventoryOwned {
    Inventory {
      items: self.items.map(|v| {
        v.into_iter()
          .map(|(_k, _v)| (alloc::borrow::Cow::Owned(_k.into_owned()), _v))
          .collect()
      }),
      label: self
        .label
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for Inventory<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:Inventory)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.items {
      writer.write_tag(1);
      writer.write_map(&v, |_w, _k, _v| {
        _w.write_string(&_k);
        _w.write_u32(*_v);
      });
    }
    if let ::core::option::Option::Some(ref v) = self.label {
      writer.write_tag(2);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:Inventory)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.items {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| {
        wire::string_size(_k.len()) + ::core::mem::size_of::<u32>()
      }));
    }
    if let ::core::option::Option::Some(ref v) = self.label {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for Inventory<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:Inventory)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.items = ::core::option::Option::Some(reader.read_map(|_r| {
            ::core::result::Result::Ok((
              ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
              _r.read_u32()?,
            ))
          })?)
        }
        2 => {
          msg.label = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "Inventory",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:Inventory)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> Inventory<'buf> {
  // @@bebop_insertion_point(message_scope:Inventory)
}

/// Empty message (all fields optional, none set).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct EmptyMessage<'buf> {
  pub unused_field: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
}

pub type EmptyMessageOwned = EmptyMessage<'static>;

impl<'buf> EmptyMessage<'buf> {
  pub fn into_owned(self) -> EmptyMessageOwned {
    EmptyMessage {
      unused_field: self
        .unused_field
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for EmptyMessage<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:EmptyMessage)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.unused_field {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:EmptyMessage)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.unused_field {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for EmptyMessage<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:EmptyMessage)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.unused_field =
            ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "EmptyMessage",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:EmptyMessage)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> EmptyMessage<'buf> {
  // @@bebop_insertion_point(message_scope:EmptyMessage)
}

/// Struct with a timestamp field.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct TimestampedEvent<'buf> {
  pub when: BebopTimestamp,
  pub what: alloc::borrow::Cow<'buf, str>,
}

pub type TimestampedEventOwned = TimestampedEvent<'static>;

impl<'buf> TimestampedEvent<'buf> {
  pub fn new(
    when: BebopTimestamp,
    what: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
  ) -> Self {
    let what = ::core::convert::Into::into(what);
    Self { when, what }
  }
}

impl<'buf> TimestampedEvent<'buf> {
  pub fn into_owned(self) -> TimestampedEventOwned {
    TimestampedEvent {
      when: self.when,
      what: alloc::borrow::Cow::Owned(self.what.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for TimestampedEvent<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:TimestampedEvent)
    writer.write_timestamp(self.when);
    writer.write_string(&self.what);
    // @@bebop_insertion_point(encode_end:TimestampedEvent)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += ::core::mem::size_of::<i64>() + ::core::mem::size_of::<i32>();
    size += wire::string_size(self.what.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for TimestampedEvent<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:TimestampedEvent)
    let when = reader.read_timestamp()?;
    let what = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    // @@bebop_insertion_point(decode_end:TimestampedEvent)
    ::core::result::Result::Ok(TimestampedEvent { when, what })
  }
}

impl<'buf> TimestampedEvent<'buf> {
  // @@bebop_insertion_point(struct_scope:TimestampedEvent)
}

/// Message with temporal fields.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct ScheduleEntry<'buf> {
  pub start: ::core::option::Option<BebopTimestamp>,
  pub duration: ::core::option::Option<BebopDuration>,
  pub label: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
}

pub type ScheduleEntryOwned = ScheduleEntry<'static>;

impl<'buf> ScheduleEntry<'buf> {
  pub fn into_owned(self) -> ScheduleEntryOwned {
    ScheduleEntry {
      start: self.start,
      duration: self.duration,
      label: self
        .label
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for ScheduleEntry<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ScheduleEntry)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(v) = self.start {
      writer.write_tag(1);
      writer.write_timestamp(v);
    }
    if let ::core::option::Option::Some(v) = self.duration {
      writer.write_tag(2);
      writer.write_duration(v);
    }
    if let ::core::option::Option::Some(ref v) = self.label {
      writer.write_tag(3);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:ScheduleEntry)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(v) = self.start {
      size += wire::tagged_size(::core::mem::size_of::<i64>() + ::core::mem::size_of::<i32>());
    }
    if let ::core::option::Option::Some(v) = self.duration {
      size += wire::tagged_size(::core::mem::size_of::<i64>() + ::core::mem::size_of::<i32>());
    }
    if let ::core::option::Option::Some(ref v) = self.label {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for ScheduleEntry<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ScheduleEntry)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => msg.start = ::core::option::Option::Some(reader.read_timestamp()?),
        2 => msg.duration = ::core::option::Option::Some(reader.read_duration()?),
        3 => {
          msg.label = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "ScheduleEntry",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:ScheduleEntry)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> ScheduleEntry<'buf> {
  // @@bebop_insertion_point(message_scope:ScheduleEntry)
}

/// Forward reference coverage: A references B before B is declared.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct ForwardRefA<'buf> {
  pub b: ForwardRefB<'buf>,
}

pub type ForwardRefAOwned = ForwardRefA<'static>;

impl<'buf> ForwardRefA<'buf> {
  pub fn new(b: ForwardRefB<'static>) -> Self {
    Self { b }
  }
}

impl<'buf> ForwardRefA<'buf> {
  pub fn into_owned(self) -> ForwardRefAOwned {
    ForwardRefA {
      b: self.b.into_owned(),
    }
  }
}

impl<'buf> BebopEncode for ForwardRefA<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ForwardRefA)
    self.b.encode(writer);
    // @@bebop_insertion_point(encode_end:ForwardRefA)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += self.b.encoded_size();
    size
  }
}

impl<'buf> BebopDecode<'buf> for ForwardRefA<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ForwardRefA)
    let b = ForwardRefB::decode(reader)?;
    // @@bebop_insertion_point(decode_end:ForwardRefA)
    ::core::result::Result::Ok(ForwardRefA { b })
  }
}

impl<'buf> ForwardRefA<'buf> {
  // @@bebop_insertion_point(struct_scope:ForwardRefA)
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct ForwardRefB<'buf> {
  pub value: alloc::borrow::Cow<'buf, str>,
}

pub type ForwardRefBOwned = ForwardRefB<'static>;

impl<'buf> ForwardRefB<'buf> {
  pub fn new(value: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>) -> Self {
    let value = ::core::convert::Into::into(value);
    Self { value }
  }
}

impl<'buf> ForwardRefB<'buf> {
  pub fn into_owned(self) -> ForwardRefBOwned {
    ForwardRefB {
      value: alloc::borrow::Cow::Owned(self.value.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for ForwardRefB<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ForwardRefB)
    writer.write_string(&self.value);
    // @@bebop_insertion_point(encode_end:ForwardRefB)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.value.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for ForwardRefB<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ForwardRefB)
    let value = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    // @@bebop_insertion_point(decode_end:ForwardRefB)
    ::core::result::Result::Ok(ForwardRefB { value })
  }
}

impl<'buf> ForwardRefB<'buf> {
  // @@bebop_insertion_point(struct_scope:ForwardRefB)
}

/// Message with deprecated fields that should still round-trip on the wire.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct DeprecatedFieldsMessage<'buf> {
  pub current_name: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  #[deprecated(note = "legacy wire compatibility")]
  pub legacy_name: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  #[deprecated]
  pub legacy_enabled: ::core::option::Option<bool>,
}

pub type DeprecatedFieldsMessageOwned = DeprecatedFieldsMessage<'static>;

impl<'buf> DeprecatedFieldsMessage<'buf> {
  pub fn into_owned(self) -> DeprecatedFieldsMessageOwned {
    DeprecatedFieldsMessage {
      current_name: self
        .current_name
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      legacy_name: self
        .legacy_name
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      legacy_enabled: self.legacy_enabled,
    }
  }
}

impl<'buf> BebopEncode for DeprecatedFieldsMessage<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:DeprecatedFieldsMessage)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.current_name {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(ref v) = self.legacy_name {
      writer.write_tag(2);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(v) = self.legacy_enabled {
      writer.write_tag(3);
      writer.write_bool(v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:DeprecatedFieldsMessage)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.current_name {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(ref v) = self.legacy_name {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(v) = self.legacy_enabled {
      size += wire::tagged_size(::core::mem::size_of::<bool>());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for DeprecatedFieldsMessage<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:DeprecatedFieldsMessage)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.current_name =
            ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        2 => {
          msg.legacy_name =
            ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        3 => msg.legacy_enabled = ::core::option::Option::Some(reader.read_bool()?),
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "DeprecatedFieldsMessage",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:DeprecatedFieldsMessage)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> DeprecatedFieldsMessage<'buf> {
  // @@bebop_insertion_point(message_scope:DeprecatedFieldsMessage)
}

/// Integer-key map coverage.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq)]
pub struct IntegerKeyMaps<'buf> {
  pub labels_by_id:
    ::core::option::Option<::bebop_runtime::HashMap<u32, alloc::borrow::Cow<'buf, str>>>,
  pub flags_by_id: ::core::option::Option<::bebop_runtime::HashMap<i64, bool>>,
}

pub type IntegerKeyMapsOwned = IntegerKeyMaps<'static>;

impl<'buf> IntegerKeyMaps<'buf> {
  pub fn into_owned(self) -> IntegerKeyMapsOwned {
    IntegerKeyMaps {
      labels_by_id: self.labels_by_id.map(|v| {
        v.into_iter()
          .map(|(_k, _v)| (_k, alloc::borrow::Cow::Owned(_v.into_owned())))
          .collect()
      }),
      flags_by_id: self.flags_by_id,
    }
  }
}

impl<'buf> BebopEncode for IntegerKeyMaps<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:IntegerKeyMaps)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.labels_by_id {
      writer.write_tag(1);
      writer.write_map(&v, |_w, _k, _v| {
        _w.write_u32(*_k);
        _w.write_string(&_v);
      });
    }
    if let ::core::option::Option::Some(ref v) = self.flags_by_id {
      writer.write_tag(2);
      writer.write_map(&v, |_w, _k, _v| {
        _w.write_i64(*_k);
        _w.write_bool(*_v);
      });
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:IntegerKeyMaps)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.labels_by_id {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| {
        ::core::mem::size_of::<u32>() + wire::string_size(_v.len())
      }));
    }
    if let ::core::option::Option::Some(ref v) = self.flags_by_id {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| {
        ::core::mem::size_of::<i64>() + ::core::mem::size_of::<bool>()
      }));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for IntegerKeyMaps<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:IntegerKeyMaps)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.labels_by_id = ::core::option::Option::Some(reader.read_map(|_r| {
            ::core::result::Result::Ok((
              _r.read_u32()?,
              ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
            ))
          })?)
        }
        2 => {
          msg.flags_by_id = ::core::option::Option::Some(
            reader.read_map(|_r| ::core::result::Result::Ok((_r.read_i64()?, _r.read_bool()?)))?,
          )
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "IntegerKeyMaps",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:IntegerKeyMaps)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> IntegerKeyMaps<'buf> {
  // @@bebop_insertion_point(message_scope:IntegerKeyMaps)
}

/// Nested type used by deep compound collections.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct NestedLeaf<'buf> {
  pub label: alloc::borrow::Cow<'buf, str>,
}

pub type NestedLeafOwned = NestedLeaf<'static>;

impl<'buf> NestedLeaf<'buf> {
  pub fn new(label: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>) -> Self {
    let label = ::core::convert::Into::into(label);
    Self { label }
  }
}

impl<'buf> NestedLeaf<'buf> {
  pub fn into_owned(self) -> NestedLeafOwned {
    NestedLeaf {
      label: alloc::borrow::Cow::Owned(self.label.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for NestedLeaf<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:NestedLeaf)
    writer.write_string(&self.label);
    // @@bebop_insertion_point(encode_end:NestedLeaf)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.label.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for NestedLeaf<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:NestedLeaf)
    let label = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    // @@bebop_insertion_point(decode_end:NestedLeaf)
    ::core::result::Result::Ok(NestedLeaf { label })
  }
}

impl<'buf> NestedLeaf<'buf> {
  // @@bebop_insertion_point(struct_scope:NestedLeaf)
}

/// Deeply nested map/array/defined-type composition.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq)]
pub struct DeepNestedCollections<'buf> {
  pub nested: ::core::option::Option<
    ::bebop_runtime::HashMap<
      alloc::borrow::Cow<'buf, str>,
      alloc::vec::Vec<::bebop_runtime::HashMap<alloc::borrow::Cow<'buf, str>, NestedLeaf<'buf>>>,
    >,
  >,
}

pub type DeepNestedCollectionsOwned = DeepNestedCollections<'static>;

impl<'buf> DeepNestedCollections<'buf> {
  pub fn into_owned(self) -> DeepNestedCollectionsOwned {
    DeepNestedCollections {
      nested: self.nested.map(|v| {
        v.into_iter()
          .map(|(_k, _v)| {
            (
              alloc::borrow::Cow::Owned(_k.into_owned()),
              _v.into_iter()
                .map(|_e| {
                  _e.into_iter()
                    .map(|(_k, _v)| (alloc::borrow::Cow::Owned(_k.into_owned()), _v.into_owned()))
                    .collect()
                })
                .collect(),
            )
          })
          .collect()
      }),
    }
  }
}

impl<'buf> BebopEncode for DeepNestedCollections<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:DeepNestedCollections)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.nested {
      writer.write_tag(1);
      writer.write_map(&v, |_w, _k, _v| {
        _w.write_string(&_k);
        _w.write_array(&_v, |_w, _el| {
          _w.write_map(&_el, |_w, _k, _v| {
            _w.write_string(&_k);
            _v.encode(_w);
          })
        });
      });
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:DeepNestedCollections)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.nested {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| {
        wire::string_size(_k.len())
          + wire::array_size(_v, |_el| {
            wire::map_size(_el, |_k, _v| {
              wire::string_size(_k.len()) + _v.encoded_size()
            })
          })
      }));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for DeepNestedCollections<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:DeepNestedCollections)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.nested = ::core::option::Option::Some(reader.read_map(|_r| {
            ::core::result::Result::Ok((
              ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
              _r.read_array(|_r| {
                _r.read_map(|_r| {
                  ::core::result::Result::Ok((
                    ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
                    NestedLeaf::decode(_r)?,
                  ))
                })
              })?,
            ))
          })?)
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "DeepNestedCollections",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:DeepNestedCollections)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> DeepNestedCollections<'buf> {
  // @@bebop_insertion_point(message_scope:DeepNestedCollections)
}

/// Struct with nested byte array (byte[][]).
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct ByteMatrix<'buf> {
  pub rows: alloc::vec::Vec<::bebop_runtime::BebopBytes<'buf>>,
}

pub type ByteMatrixOwned = ByteMatrix<'static>;

impl<'buf> ByteMatrix<'buf> {
  pub fn new(rows: alloc::vec::Vec<::bebop_runtime::BebopBytes<'static>>) -> Self {
    let rows = rows
      .into_iter()
      .map(|_e| <::bebop_runtime::BebopBytes as ::core::convert::From<_>>::from(_e))
      .collect();
    Self { rows }
  }
}

impl<'buf> ByteMatrix<'buf> {
  pub fn into_owned(self) -> ByteMatrixOwned {
    ByteMatrix {
      rows: self.rows.into_iter().map(|_e| _e.into_owned()).collect(),
    }
  }
}

impl<'buf> BebopEncode for ByteMatrix<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ByteMatrix)
    writer.write_array(&self.rows, |_w, _el| _w.write_byte_array(&_el));
    // @@bebop_insertion_point(encode_end:ByteMatrix)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::array_size(&self.rows, |_el| wire::byte_array_size(_el.len()));
    size
  }
}

impl<'buf> BebopDecode<'buf> for ByteMatrix<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ByteMatrix)
    let rows = reader.read_array(|_r| {
      ::core::result::Result::Ok(::bebop_runtime::BebopBytes::borrowed(_r.read_byte_slice()?))
    })?;
    // @@bebop_insertion_point(decode_end:ByteMatrix)
    ::core::result::Result::Ok(ByteMatrix { rows })
  }
}

impl<'buf> ByteMatrix<'buf> {
  // @@bebop_insertion_point(struct_scope:ByteMatrix)
}

/// Struct with map containing byte array values.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct ByteTagMap<'buf> {
  pub entries:
    ::bebop_runtime::HashMap<alloc::borrow::Cow<'buf, str>, ::bebop_runtime::BebopBytes<'buf>>,
}

pub type ByteTagMapOwned = ByteTagMap<'static>;

impl<'buf> ByteTagMap<'buf> {
  pub fn new(
    entries: ::bebop_runtime::HashMap<alloc::string::String, ::bebop_runtime::BebopBytes<'static>>,
  ) -> Self {
    let entries = entries
      .into_iter()
      .map(|(_k, _v)| {
        (
          alloc::borrow::Cow::Owned(_k),
          <::bebop_runtime::BebopBytes as ::core::convert::From<_>>::from(_v),
        )
      })
      .collect();
    Self { entries }
  }
}

impl<'buf> ByteTagMap<'buf> {
  pub fn into_owned(self) -> ByteTagMapOwned {
    ByteTagMap {
      entries: self
        .entries
        .into_iter()
        .map(|(_k, _v)| (alloc::borrow::Cow::Owned(_k.into_owned()), _v.into_owned()))
        .collect(),
    }
  }
}

impl<'buf> BebopEncode for ByteTagMap<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ByteTagMap)
    writer.write_map(&self.entries, |_w, _k, _v| {
      _w.write_string(&_k);
      _w.write_byte_array(&_v);
    });
    // @@bebop_insertion_point(encode_end:ByteTagMap)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::map_size(&self.entries, |_k, _v| {
      wire::string_size(_k.len()) + wire::byte_array_size(_v.len())
    });
    size
  }
}

impl<'buf> BebopDecode<'buf> for ByteTagMap<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ByteTagMap)
    let entries = reader.read_map(|_r| {
      ::core::result::Result::Ok((
        ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
        ::core::result::Result::Ok(::bebop_runtime::BebopBytes::borrowed(_r.read_byte_slice()?))?,
      ))
    })?;
    // @@bebop_insertion_point(decode_end:ByteTagMap)
    ::core::result::Result::Ok(ByteTagMap { entries })
  }
}

impl<'buf> ByteTagMap<'buf> {
  // @@bebop_insertion_point(struct_scope:ByteTagMap)
}

/// Message with byte array field — tests Option<BebopBytes> serde.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
pub struct ByteArrayMessage<'buf> {
  pub label: ::core::option::Option<alloc::borrow::Cow<'buf, str>>,
  pub payload: ::core::option::Option<::bebop_runtime::BebopBytes<'buf>>,
}

pub type ByteArrayMessageOwned = ByteArrayMessage<'static>;

impl<'buf> ByteArrayMessage<'buf> {
  pub fn into_owned(self) -> ByteArrayMessageOwned {
    ByteArrayMessage {
      label: self
        .label
        .map(|v| alloc::borrow::Cow::Owned(v.into_owned())),
      payload: self.payload.map(|v| v.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for ByteArrayMessage<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ByteArrayMessage)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.label {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    if let ::core::option::Option::Some(ref v) = self.payload {
      writer.write_tag(2);
      writer.write_byte_array(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:ByteArrayMessage)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.label {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let ::core::option::Option::Some(ref v) = self.payload {
      size += wire::tagged_size(wire::byte_array_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for ByteArrayMessage<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ByteArrayMessage)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.label = ::core::option::Option::Some(alloc::borrow::Cow::Borrowed(reader.read_str()?))
        }
        2 => {
          msg.payload = ::core::option::Option::Some(::bebop_runtime::BebopBytes::borrowed(
            reader.read_byte_slice()?,
          ))
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "ByteArrayMessage",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:ByteArrayMessage)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> ByteArrayMessage<'buf> {
  // @@bebop_insertion_point(message_scope:ByteArrayMessage)
}

/// Message with nested byte arrays and maps.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default, PartialEq, Eq)]
pub struct ByteCollectionMessage<'buf> {
  pub matrix: ::core::option::Option<alloc::vec::Vec<::bebop_runtime::BebopBytes<'buf>>>,
  pub tagged: ::core::option::Option<
    ::bebop_runtime::HashMap<alloc::borrow::Cow<'buf, str>, ::bebop_runtime::BebopBytes<'buf>>,
  >,
}

pub type ByteCollectionMessageOwned = ByteCollectionMessage<'static>;

impl<'buf> ByteCollectionMessage<'buf> {
  pub fn into_owned(self) -> ByteCollectionMessageOwned {
    ByteCollectionMessage {
      matrix: self
        .matrix
        .map(|v| v.into_iter().map(|_e| _e.into_owned()).collect()),
      tagged: self.tagged.map(|v| {
        v.into_iter()
          .map(|(_k, _v)| (alloc::borrow::Cow::Owned(_k.into_owned()), _v.into_owned()))
          .collect()
      }),
    }
  }
}

impl<'buf> BebopEncode for ByteCollectionMessage<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:ByteCollectionMessage)
    let pos = writer.reserve_message_length();
    // NOTE: Deprecated fields are currently encoded and decoded like normal fields.
    // The GRAMMAR.md spec says deprecated message fields should be skipped during
    // encoding and decoding. The C plugin (plugins/c/src/generator.c:3446) skips
    // them on encode/size but still decodes them. The Swift plugin encodes them
    // normally. This behavior should be revisited once the spec intent is clarified.
    if let ::core::option::Option::Some(ref v) = self.matrix {
      writer.write_tag(1);
      writer.write_array(&v, |_w, _el| _w.write_byte_array(&_el));
    }
    if let ::core::option::Option::Some(ref v) = self.tagged {
      writer.write_tag(2);
      writer.write_map(&v, |_w, _k, _v| {
        _w.write_string(&_k);
        _w.write_byte_array(&_v);
      });
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
    // @@bebop_insertion_point(encode_end:ByteCollectionMessage)
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let ::core::option::Option::Some(ref v) = self.matrix {
      size += wire::tagged_size(wire::array_size(v, |_el| wire::byte_array_size(_el.len())));
    }
    if let ::core::option::Option::Some(ref v) = self.tagged {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| {
        wire::string_size(_k.len()) + wire::byte_array_size(_v.len())
      }));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for ByteCollectionMessage<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:ByteCollectionMessage)
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = <Self as ::core::default::Default>::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 {
        break;
      }
      match tag {
        1 => {
          msg.matrix = ::core::option::Option::Some(reader.read_array(|_r| {
            ::core::result::Result::Ok(::bebop_runtime::BebopBytes::borrowed(_r.read_byte_slice()?))
          })?)
        }
        2 => {
          msg.tagged = ::core::option::Option::Some(reader.read_map(|_r| {
            ::core::result::Result::Ok((
              ::core::result::Result::Ok(alloc::borrow::Cow::Borrowed(_r.read_str()?))?,
              ::core::result::Result::Ok(::bebop_runtime::BebopBytes::borrowed(
                _r.read_byte_slice()?,
              ))?,
            ))
          })?)
        }
        tag => {
          return ::core::result::Result::Err(DecodeError::InvalidField {
            type_name: "ByteCollectionMessage",
            tag,
          });
        }
      }
    }
    // @@bebop_insertion_point(decode_end:ByteCollectionMessage)
    ::core::result::Result::Ok(msg)
  }
}

impl<'buf> ByteCollectionMessage<'buf> {
  // @@bebop_insertion_point(message_scope:ByteCollectionMessage)
}

/// Struct with a UUID field for serde round-trip testing.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
pub struct UuidHolder<'buf> {
  pub id: ::bebop_runtime::Uuid,
  pub label: alloc::borrow::Cow<'buf, str>,
}

pub type UuidHolderOwned = UuidHolder<'static>;

impl<'buf> UuidHolder<'buf> {
  pub fn new(
    id: ::bebop_runtime::Uuid,
    label: impl ::core::convert::Into<alloc::borrow::Cow<'buf, str>>,
  ) -> Self {
    let label = ::core::convert::Into::into(label);
    Self { id, label }
  }
}

impl<'buf> UuidHolder<'buf> {
  pub fn into_owned(self) -> UuidHolderOwned {
    UuidHolder {
      id: self.id,
      label: alloc::borrow::Cow::Owned(self.label.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for UuidHolder<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    // @@bebop_insertion_point(encode_start:UuidHolder)
    writer.write_uuid(self.id);
    writer.write_string(&self.label);
    // @@bebop_insertion_point(encode_end:UuidHolder)
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += ::core::mem::size_of::<::bebop_runtime::Uuid>();
    size += wire::string_size(self.label.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for UuidHolder<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> ::core::result::Result<Self, DecodeError> {
    // @@bebop_insertion_point(decode_start:UuidHolder)
    let id = reader.read_uuid()?;
    let label = alloc::borrow::Cow::Borrowed(reader.read_str()?);
    // @@bebop_insertion_point(decode_end:UuidHolder)
    ::core::result::Result::Ok(UuidHolder { id, label })
  }
}

impl<'buf> UuidHolder<'buf> {
  // @@bebop_insertion_point(struct_scope:UuidHolder)
}

// @@bebop_insertion_point(eof)
