// Code generated by bebopc-gen-rust. DO NOT EDIT.
// source: /Users/mayfield/vendor/bebop-next/plugins/rust/integration-tests/schemas/test_types.bop
// bebopc 0.1.0
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE

#![allow(warnings)]

extern crate alloc;
use alloc::borrow::Cow;
use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;
use core::mem::size_of;
use bebop_runtime::HashMap;
use bebop_runtime::{BebopReader, BebopWriter, BebopEncode, BebopDecode, BebopFlags, DecodeError, f16, bf16};
use bebop_runtime::wire_size as wire;

/// Simple enum with uint8 base type.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Color {
  Unknown = 0,
  Red = 1,
  Green = 2,
  Blue = 3,
}

impl core::convert::TryFrom<u8> for Color {
  type Error = DecodeError;
  fn try_from(value: u8) -> Result<Self, DecodeError> {
    match value {
      0 => Ok(Self::Unknown),
      1 => Ok(Self::Red),
      2 => Ok(Self::Green),
      3 => Ok(Self::Blue),
      _ => Err(DecodeError::InvalidEnum { type_name: "Color", value: value as u64 }),
    }
  }
}

impl From<Color> for u8 {
  fn from(value: Color) -> u8 { value as u8 }
}

impl Color {
  pub const FIXED_ENCODED_SIZE: usize = 1;
}

impl BebopEncode for Color {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_byte(*self as u8);
  }

  fn encoded_size(&self) -> usize { Self::FIXED_ENCODED_SIZE }
}

impl<'buf> BebopDecode<'buf> for Color {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    Self::try_from(reader.read_byte()?)
  }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Permissions(pub u8);

#[allow(non_upper_case_globals)]
impl Permissions {
  pub const FIXED_ENCODED_SIZE: usize = 1;
  pub const NONE: Self = Self(0);
  pub const READ: Self = Self(1);
  pub const WRITE: Self = Self(2);
  pub const EXECUTE: Self = Self(4);
  pub const ALL: Self = Self(7);
}

impl BebopFlags for Permissions {
  type Bits = u8;
  const ALL_BITS: Self::Bits = 7;
  fn bits(self) -> Self::Bits { self.0 }
  fn from_bits_retain(bits: Self::Bits) -> Self { Self(bits) }
}

impl core::ops::BitOr for Permissions { type Output = Self; fn bitor(self, rhs: Self) -> Self { Self(self.0 | rhs.0) } }
impl core::ops::BitOrAssign for Permissions { fn bitor_assign(&mut self, rhs: Self) { self.0 |= rhs.0; } }
impl core::ops::BitAnd for Permissions { type Output = Self; fn bitand(self, rhs: Self) -> Self { Self(self.0 & rhs.0) } }
impl core::ops::BitAndAssign for Permissions { fn bitand_assign(&mut self, rhs: Self) { self.0 &= rhs.0; } }
impl core::ops::BitXor for Permissions { type Output = Self; fn bitxor(self, rhs: Self) -> Self { Self(self.0 ^ rhs.0) } }
impl core::ops::BitXorAssign for Permissions { fn bitxor_assign(&mut self, rhs: Self) { self.0 ^= rhs.0; } }
impl core::ops::Not for Permissions { type Output = Self; fn not(self) -> Self { Self(!self.0) } }
impl core::ops::Sub for Permissions { type Output = Self; fn sub(self, rhs: Self) -> Self { Self(self.0 & !rhs.0) } }

/// Constants used to validate Rust const generation.
pub const P_CASE: u8 = 18u8;

pub const EXAMPLE_CONST_INT32: i32 = -123i32;

pub const EXAMPLE_CONST_UINT64: u64 = 1254130450431u64;

pub const EXAMPLE_CONST_FLOAT64: f64 = 123456780000.0f64;

pub const EXAMPLE_CONST_INF: f64 = f64::INFINITY;

pub const EXAMPLE_CONST_NEG_INF: f64 = f64::NEG_INFINITY;

pub const EXAMPLE_CONST_NAN: f64 = f64::NAN;

pub const EXAMPLE_CONST_FALSE: bool = false;

pub const EXAMPLE_CONST_TRUE: bool = true;

pub const HTTP_STATUS_OK: u32 = 200u32;

pub const FEATURE_FLAG_ENABLED: bool = true;

pub const EXAMPLE_CONST_STRING: &str = "hello \"world\"\nwith newlines";

pub const EXAMPLE_CONST_GUID: [u8; 16] = [0xE2, 0x15, 0xA9, 0x46, 0xB2, 0x6F, 0x45, 0x67, 0xA2, 0x76, 0x13, 0x13, 0x6F, 0x0A, 0x17, 0x08];

pub const EXAMPLE_CONST_F16: f16 = f16::from_f64_const(1.5f64);

pub const EXAMPLE_CONST_BF16: bf16 = bf16::from_f64_const(1.5f64);

pub const EXAMPLE_CONST_F16_INF: f16 = f16::INFINITY;

pub const EXAMPLE_CONST_BF16_NEG_INF: bf16 = bf16::NEG_INFINITY;

pub const EXAMPLE_CONST_F16_NAN: f16 = f16::NAN;

pub const EXAMPLE_CONST_BF16_NAN: bf16 = bf16::NAN;

pub const EXAMPLE_CONST_F16_FROM_INT: f16 = f16::from_f64_const(1f64);

pub const EXAMPLE_CONST_BF16_FROM_INT: bf16 = bf16::from_f64_const(2f64);

/// Fixed-size struct (all scalar fields).
#[derive(Debug, Clone)]
pub struct Point {
  pub x: f32,
  pub y: f32,
}

impl Point {
  pub const FIXED_ENCODED_SIZE: usize = size_of::<f32>() + size_of::<f32>();

  pub fn new(x: f32, y: f32) -> Self {
    Self { x, y }
  }
}

impl BebopEncode for Point {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_f32(self.x);
    writer.write_f32(self.y);
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Point {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let x = reader.read_f32()?;
    let y = reader.read_f32()?;
    Ok(Point { x, y })
  }
}

/// Fixed-size struct referencing another struct and an enum.
#[derive(Debug, Clone)]
pub struct Pixel {
  pub position: Point,
  pub color: Color,
  pub alpha: u8,
}

impl Pixel {
  pub const FIXED_ENCODED_SIZE: usize =
    Point::FIXED_ENCODED_SIZE
    + Color::FIXED_ENCODED_SIZE
    + size_of::<u8>();

  pub fn new(position: Point, color: Color, alpha: u8) -> Self {
    Self { position, color, alpha }
  }
}

impl BebopEncode for Pixel {
  fn encode(&self, writer: &mut BebopWriter) {
    self.position.encode(writer);
    self.color.encode(writer);
    writer.write_byte(self.alpha);
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Pixel {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let position = Point::decode(reader)?;
    let color = Color::decode(reader)?;
    let alpha = reader.read_byte()?;
    Ok(Pixel { position, color, alpha })
  }
}

/// Variable-size struct with a string field (needs lifetime / Cow).
#[derive(Debug, Clone)]
pub struct Person<'buf> {
  pub name: Cow<'buf, str>,
  pub age: u32,
}

pub type PersonOwned = Person<'static>;

impl<'buf> Person<'buf> {
  pub fn new(name: impl Into<Cow<'buf, str>>, age: u32) -> Self {
    let name = name.into();
    Self { name, age }
  }
}

impl<'buf> Person<'buf> {
  pub fn into_owned(self) -> PersonOwned {
    Person {
      name: Cow::Owned(self.name.into_owned()),
      age: self.age,
    }
  }
}

impl<'buf> BebopEncode for Person<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_string(&self.name);
    writer.write_u32(self.age);
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.name.len());
    size += size_of::<u32>();
    size
  }
}

impl<'buf> BebopDecode<'buf> for Person<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let name = Cow::Borrowed(reader.read_str()?);
    let age = reader.read_u32()?;
    Ok(Person { name, age })
  }
}

/// Variable-size struct with a byte array field (needs lifetime / Cow).
#[derive(Debug, Clone)]
pub struct BinaryPayload<'buf> {
  pub tag: u32,
  pub data: Cow<'buf, [u8]>,
}

pub type BinaryPayloadOwned = BinaryPayload<'static>;

impl<'buf> BinaryPayload<'buf> {
  pub fn new(tag: u32, data: impl Into<Cow<'buf, [u8]>>) -> Self {
    let data = data.into();
    Self { tag, data }
  }
}

impl<'buf> BinaryPayload<'buf> {
  pub fn into_owned(self) -> BinaryPayloadOwned {
    BinaryPayload {
      tag: self.tag,
      data: Cow::Owned(self.data.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for BinaryPayload<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_u32(self.tag);
    writer.write_byte_array(&self.data);
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += size_of::<u32>();
    size += wire::byte_array_size(self.data.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for BinaryPayload<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let tag = reader.read_u32()?;
    let data = Cow::Borrowed(reader.read_byte_slice()?);
    Ok(BinaryPayload { tag, data })
  }
}

/// Message with various field types: scalars, strings, arrays, maps.
#[derive(Debug, Clone, Default)]
pub struct UserProfile<'buf> {
  pub display_name: Option<Cow<'buf, str>>,
  pub email: Option<Cow<'buf, str>>,
  pub age: Option<u32>,
  pub active: Option<bool>,
  pub tags: Option<Vec<Cow<'buf, str>>>,
  pub metadata: Option<HashMap<Cow<'buf, str>, Cow<'buf, str>>>,
  pub permissions: Option<Permissions>,
}

pub type UserProfileOwned = UserProfile<'static>;

impl<'buf> UserProfile<'buf> {
  pub fn into_owned(self) -> UserProfileOwned {
    UserProfile {
      display_name: self.display_name.map(|v| Cow::Owned(v.into_owned())),
      email: self.email.map(|v| Cow::Owned(v.into_owned())),
      age: self.age,
      active: self.active,
      tags: self.tags.map(|v| v.into_iter().map(|_e| Cow::Owned(_e.into_owned())).collect()),
      metadata: self.metadata.map(|v| v.into_iter().map(|(_k, _v)| (Cow::Owned(_k.into_owned()), Cow::Owned(_v.into_owned()))).collect()),
      permissions: self.permissions,
    }
  }
}

impl<'buf> BebopEncode for UserProfile<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(ref v) = self.display_name {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    if let Some(ref v) = self.email {
      writer.write_tag(2);
      writer.write_string(&v);
    }
    if let Some(v) = self.age {
      writer.write_tag(3);
      writer.write_u32(v);
    }
    if let Some(v) = self.active {
      writer.write_tag(4);
      writer.write_bool(v);
    }
    if let Some(ref v) = self.tags {
      writer.write_tag(5);
      writer.write_array(&v, |_w, _el| _w.write_string(_el));
    }
    if let Some(ref v) = self.metadata {
      writer.write_tag(6);
      writer.write_map(&v, |_w, _k, _v| { _w.write_string(&_k); _w.write_string(&_v); });
    }
    if let Some(ref v) = self.permissions {
      writer.write_tag(7);
      v.encode(writer);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(ref v) = self.display_name {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let Some(ref v) = self.email {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let Some(v) = self.age {
      size += wire::tagged_size(size_of::<u32>());
    }
    if let Some(v) = self.active {
      size += wire::tagged_size(size_of::<bool>());
    }
    if let Some(ref v) = self.tags {
      size += wire::tagged_size(wire::array_size(v, |_el| wire::string_size(_el.len())));
    }
    if let Some(ref v) = self.metadata {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| wire::string_size(_k.len()) + wire::string_size(_v.len())));
    }
    if let Some(ref v) = self.permissions {
      size += wire::tagged_size(v.encoded_size());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for UserProfile<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.display_name = Some(Cow::Borrowed(reader.read_str()?)),
        2 => msg.email = Some(Cow::Borrowed(reader.read_str()?)),
        3 => msg.age = Some(reader.read_u32()?),
        4 => msg.active = Some(reader.read_bool()?),
        5 => msg.tags = Some(reader.read_array(|_r| Ok(Cow::Borrowed(_r.read_str()?)))?),
        6 => msg.metadata = Some(reader.read_map(|_r| Ok((Ok(Cow::Borrowed(_r.read_str()?))?, Ok(Cow::Borrowed(_r.read_str()?))?)))?),
        7 => msg.permissions = Some(Permissions::decode(reader)?),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

/// Message referencing fixed-size and enum defined types.
#[derive(Debug, Clone, Default)]
pub struct DrawCommand<'buf> {
  pub target: Option<Point>,
  pub color: Option<Color>,
  pub label: Option<Cow<'buf, str>>,
  pub thickness: Option<f32>,
}

pub type DrawCommandOwned = DrawCommand<'static>;

impl<'buf> DrawCommand<'buf> {
  pub fn into_owned(self) -> DrawCommandOwned {
    DrawCommand {
      target: self.target,
      color: self.color,
      label: self.label.map(|v| Cow::Owned(v.into_owned())),
      thickness: self.thickness,
    }
  }
}

impl<'buf> BebopEncode for DrawCommand<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(ref v) = self.target {
      writer.write_tag(1);
      v.encode(writer);
    }
    if let Some(ref v) = self.color {
      writer.write_tag(2);
      v.encode(writer);
    }
    if let Some(ref v) = self.label {
      writer.write_tag(3);
      writer.write_string(&v);
    }
    if let Some(v) = self.thickness {
      writer.write_tag(4);
      writer.write_f32(v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(ref v) = self.target {
      size += wire::tagged_size(v.encoded_size());
    }
    if let Some(ref v) = self.color {
      size += wire::tagged_size(v.encoded_size());
    }
    if let Some(ref v) = self.label {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    if let Some(v) = self.thickness {
      size += wire::tagged_size(size_of::<f32>());
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for DrawCommand<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.target = Some(Point::decode(reader)?),
        2 => msg.color = Some(Color::decode(reader)?),
        3 => msg.label = Some(Cow::Borrowed(reader.read_str()?)),
        4 => msg.thickness = Some(reader.read_f32()?),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

/// Struct used as a union branch (variable-size due to string field).
#[derive(Debug, Clone)]
pub struct TextLabel<'buf> {
  pub position: Point,
  pub text: Cow<'buf, str>,
}

pub type TextLabelOwned = TextLabel<'static>;

impl<'buf> TextLabel<'buf> {
  pub fn new(position: Point, text: impl Into<Cow<'buf, str>>) -> Self {
    let text = text.into();
    Self { position, text }
  }
}

impl<'buf> TextLabel<'buf> {
  pub fn into_owned(self) -> TextLabelOwned {
    TextLabel {
      position: self.position,
      text: Cow::Owned(self.text.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for TextLabel<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    self.position.encode(writer);
    writer.write_string(&self.text);
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += self.position.encoded_size();
    size += wire::string_size(self.text.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for TextLabel<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let position = Point::decode(reader)?;
    let text = Cow::Borrowed(reader.read_str()?);
    Ok(TextLabel { position, text })
  }
}

/// Union with type-ref branches covering fixed and variable inner types.
#[derive(Debug, Clone)]
pub enum Shape<'buf> {
  Point(Point),
  Pixel(Pixel),
  Label(TextLabel<'buf>),
  Unknown(u8, Cow<'buf, [u8]>),
}

pub type ShapeOwned = Shape<'static>;

impl<'buf> Shape<'buf> {
  pub fn into_owned(self) -> ShapeOwned {
    match self {
      Self::Point(inner) => Shape::Point(inner),
      Self::Pixel(inner) => Shape::Pixel(inner),
      Self::Label(inner) => Shape::Label(inner.into_owned()),
      Self::Unknown(disc, data) => Shape::Unknown(disc, Cow::Owned(data.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for Shape<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    match self {
      Self::Point(inner) => { writer.write_byte(1); inner.encode(writer); }
      Self::Pixel(inner) => { writer.write_byte(2); inner.encode(writer); }
      Self::Label(inner) => { writer.write_byte(3); inner.encode(writer); }
      Self::Unknown(disc, data) => { writer.write_byte(*disc); writer.write_raw(data); }
    }
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    wire::WIRE_LEN_PREFIX_SIZE + match self {
      Self::Point(inner) => wire::tagged_size(inner.encoded_size()),
      Self::Pixel(inner) => wire::tagged_size(inner.encoded_size()),
      Self::Label(inner) => wire::tagged_size(inner.encoded_size()),
      Self::Unknown(_, data) => wire::tagged_size(data.len()),
    }
  }
}

impl<'buf> BebopDecode<'buf> for Shape<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let start = reader.position();
    let discriminator = reader.read_byte()?;
    match discriminator {
      1 => Ok(Self::Point(Point::decode(reader)?)),
      2 => Ok(Self::Pixel(Pixel::decode(reader)?)),
      3 => Ok(Self::Label(TextLabel::decode(reader)?)),
      _ => {
        let remaining = length - (reader.position() - start);
        let data = reader.read_raw_bytes(remaining)?;
        Ok(Self::Unknown(discriminator, Cow::Borrowed(data)))
      }
    }
  }
}

/// Fixed-array struct (compile-time known element count).
#[derive(Debug, Clone)]
pub struct Matrix2x2 {
  pub values: [f32; 4],
}

impl Matrix2x2 {
  pub const FIXED_ENCODED_SIZE: usize = size_of::<f32>() * 4;

  pub fn new(values: [f32; 4]) -> Self {
    Self { values }
  }
}

impl BebopEncode for Matrix2x2 {
  fn encode(&self, writer: &mut BebopWriter) {
    for _el in self.values.iter() { writer.write_f32(*_el) };
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for Matrix2x2 {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let values = { let mut _arr = [Default::default(); 4]; for _i in 0..4 { _arr[_i] = reader.read_f32()?; } Ok(_arr) }?;
    Ok(Matrix2x2 { values })
  }
}

/// Fixed-size and variable-size half-precision scalar coverage.
#[derive(Debug, Clone)]
pub struct HalfPrecisionScalars {
  pub f16_val: f16,
  pub bf16_val: bf16,
}

impl HalfPrecisionScalars {
  pub const FIXED_ENCODED_SIZE: usize = size_of::<f16>() + size_of::<bf16>();

  pub fn new(f16_val: f16, bf16_val: bf16) -> Self {
    Self { f16_val, bf16_val }
  }
}

impl BebopEncode for HalfPrecisionScalars {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_f16(self.f16_val);
    writer.write_bf16(self.bf16_val);
  }

  fn encoded_size(&self) -> usize {
    Self::FIXED_ENCODED_SIZE
  }
}

impl<'buf> BebopDecode<'buf> for HalfPrecisionScalars {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let f16_val = reader.read_f16()?;
    let bf16_val = reader.read_bf16()?;
    Ok(HalfPrecisionScalars { f16_val, bf16_val })
  }
}

#[derive(Debug, Clone)]
pub struct HalfPrecisionArrays {
  pub f16_dynamic: Vec<f16>,
  pub bf16_dynamic: Vec<bf16>,
  pub f16_fixed: [f16; 4],
  pub bf16_fixed: [bf16; 4],
}

impl HalfPrecisionArrays {
  pub fn new(f16_dynamic: Vec<f16>, bf16_dynamic: Vec<bf16>, f16_fixed: [f16; 4], bf16_fixed: [bf16; 4]) -> Self {
    Self { f16_dynamic, bf16_dynamic, f16_fixed, bf16_fixed }
  }
}

impl BebopEncode for HalfPrecisionArrays {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_array(&self.f16_dynamic, |_w, _el| _w.write_f16(*_el));
    writer.write_array(&self.bf16_dynamic, |_w, _el| _w.write_bf16(*_el));
    for _el in self.f16_fixed.iter() { writer.write_f16(*_el) };
    for _el in self.bf16_fixed.iter() { writer.write_bf16(*_el) };
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::array_size(&self.f16_dynamic, |_el| (size_of::<f16>()));
    size += wire::array_size(&self.bf16_dynamic, |_el| (size_of::<bf16>()));
    size += 4usize * (size_of::<f16>());
    size += 4usize * (size_of::<bf16>());
    size
  }
}

impl<'buf> BebopDecode<'buf> for HalfPrecisionArrays {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let f16_dynamic = reader.read_array(|_r| _r.read_f16())?;
    let bf16_dynamic = reader.read_array(|_r| _r.read_bf16())?;
    let f16_fixed = { let mut _arr = [Default::default(); 4]; for _i in 0..4 { _arr[_i] = reader.read_f16()?; } Ok(_arr) }?;
    let bf16_fixed = { let mut _arr = [Default::default(); 4]; for _i in 0..4 { _arr[_i] = reader.read_bf16()?; } Ok(_arr) }?;
    Ok(HalfPrecisionArrays { f16_dynamic, bf16_dynamic, f16_fixed, bf16_fixed })
  }
}

#[derive(Debug, Clone, Default)]
pub struct HalfPrecisionMessage {
  pub f16_val: Option<f16>,
  pub bf16_val: Option<bf16>,
  pub f16_arr: Option<Vec<f16>>,
  pub bf16_arr: Option<Vec<bf16>>,
}

impl BebopEncode for HalfPrecisionMessage {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(v) = self.f16_val {
      writer.write_tag(1);
      writer.write_f16(v);
    }
    if let Some(v) = self.bf16_val {
      writer.write_tag(2);
      writer.write_bf16(v);
    }
    if let Some(ref v) = self.f16_arr {
      writer.write_tag(3);
      writer.write_array(&v, |_w, _el| _w.write_f16(*_el));
    }
    if let Some(ref v) = self.bf16_arr {
      writer.write_tag(4);
      writer.write_array(&v, |_w, _el| _w.write_bf16(*_el));
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(v) = self.f16_val {
      size += wire::tagged_size(size_of::<f16>());
    }
    if let Some(v) = self.bf16_val {
      size += wire::tagged_size(size_of::<bf16>());
    }
    if let Some(ref v) = self.f16_arr {
      size += wire::tagged_size(wire::array_size(v, |_el| (size_of::<f16>())));
    }
    if let Some(ref v) = self.bf16_arr {
      size += wire::tagged_size(wire::array_size(v, |_el| (size_of::<bf16>())));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for HalfPrecisionMessage {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.f16_val = Some(reader.read_f16()?),
        2 => msg.bf16_val = Some(reader.read_bf16()?),
        3 => msg.f16_arr = Some(reader.read_array(|_r| _r.read_f16())?),
        4 => msg.bf16_arr = Some(reader.read_array(|_r| _r.read_bf16())?),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

/// Struct with multiple string fields (all need Cow).
#[derive(Debug, Clone)]
pub struct Address<'buf> {
  pub street: Cow<'buf, str>,
  pub city: Cow<'buf, str>,
  pub country: Cow<'buf, str>,
  pub zip_code: Cow<'buf, str>,
}

pub type AddressOwned = Address<'static>;

impl<'buf> Address<'buf> {
  pub fn new(street: impl Into<Cow<'buf, str>>, city: impl Into<Cow<'buf, str>>, country: impl Into<Cow<'buf, str>>, zip_code: impl Into<Cow<'buf, str>>) -> Self {
    let street = street.into();
    let city = city.into();
    let country = country.into();
    let zip_code = zip_code.into();
    Self { street, city, country, zip_code }
  }
}

impl<'buf> Address<'buf> {
  pub fn into_owned(self) -> AddressOwned {
    Address {
      street: Cow::Owned(self.street.into_owned()),
      city: Cow::Owned(self.city.into_owned()),
      country: Cow::Owned(self.country.into_owned()),
      zip_code: Cow::Owned(self.zip_code.into_owned()),
    }
  }
}

impl<'buf> BebopEncode for Address<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    writer.write_string(&self.street);
    writer.write_string(&self.city);
    writer.write_string(&self.country);
    writer.write_string(&self.zip_code);
  }

  fn encoded_size(&self) -> usize {
    let mut size = 0;
    size += wire::string_size(self.street.len());
    size += wire::string_size(self.city.len());
    size += wire::string_size(self.country.len());
    size += wire::string_size(self.zip_code.len());
    size
  }
}

impl<'buf> BebopDecode<'buf> for Address<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let street = Cow::Borrowed(reader.read_str()?);
    let city = Cow::Borrowed(reader.read_str()?);
    let country = Cow::Borrowed(reader.read_str()?);
    let zip_code = Cow::Borrowed(reader.read_str()?);
    Ok(Address { street, city, country, zip_code })
  }
}

/// Message with array-of-defined-type and nested references.
#[derive(Debug, Clone, Default)]
pub struct Scene<'buf> {
  pub shapes: Option<Vec<Shape<'buf>>>,
  pub background: Option<Color>,
  pub title: Option<Cow<'buf, str>>,
}

pub type SceneOwned = Scene<'static>;

impl<'buf> Scene<'buf> {
  pub fn into_owned(self) -> SceneOwned {
    Scene {
      shapes: self.shapes.map(|v| v.into_iter().map(|_e| _e.into_owned()).collect()),
      background: self.background,
      title: self.title.map(|v| Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for Scene<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(ref v) = self.shapes {
      writer.write_tag(1);
      writer.write_array(&v, |_w, _el| _el.encode(_w));
    }
    if let Some(ref v) = self.background {
      writer.write_tag(2);
      v.encode(writer);
    }
    if let Some(ref v) = self.title {
      writer.write_tag(3);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(ref v) = self.shapes {
      size += wire::tagged_size(wire::array_size(v, |_el| _el.encoded_size()));
    }
    if let Some(ref v) = self.background {
      size += wire::tagged_size(v.encoded_size());
    }
    if let Some(ref v) = self.title {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for Scene<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.shapes = Some(reader.read_array(|_r| Shape::decode(_r))?),
        2 => msg.background = Some(Color::decode(reader)?),
        3 => msg.title = Some(Cow::Borrowed(reader.read_str()?)),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

/// Message with map[string, defined-type] value.
#[derive(Debug, Clone, Default)]
pub struct Inventory<'buf> {
  pub items: Option<HashMap<Cow<'buf, str>, u32>>,
  pub label: Option<Cow<'buf, str>>,
}

pub type InventoryOwned = Inventory<'static>;

impl<'buf> Inventory<'buf> {
  pub fn into_owned(self) -> InventoryOwned {
    Inventory {
      items: self.items.map(|v| v.into_iter().map(|(_k, _v)| (Cow::Owned(_k.into_owned()), _v)).collect()),
      label: self.label.map(|v| Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for Inventory<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(ref v) = self.items {
      writer.write_tag(1);
      writer.write_map(&v, |_w, _k, _v| { _w.write_string(&_k); _w.write_u32(*_v); });
    }
    if let Some(ref v) = self.label {
      writer.write_tag(2);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(ref v) = self.items {
      size += wire::tagged_size(wire::map_size(v, |_k, _v| wire::string_size(_k.len()) + size_of::<u32>()));
    }
    if let Some(ref v) = self.label {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for Inventory<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.items = Some(reader.read_map(|_r| Ok((Ok(Cow::Borrowed(_r.read_str()?))?, _r.read_u32()?)))?),
        2 => msg.label = Some(Cow::Borrowed(reader.read_str()?)),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

/// Empty message (all fields optional, none set).
#[derive(Debug, Clone, Default)]
pub struct EmptyMessage<'buf> {
  pub unused_field: Option<Cow<'buf, str>>,
}

pub type EmptyMessageOwned = EmptyMessage<'static>;

impl<'buf> EmptyMessage<'buf> {
  pub fn into_owned(self) -> EmptyMessageOwned {
    EmptyMessage {
      unused_field: self.unused_field.map(|v| Cow::Owned(v.into_owned())),
    }
  }
}

impl<'buf> BebopEncode for EmptyMessage<'buf> {
  fn encode(&self, writer: &mut BebopWriter) {
    let pos = writer.reserve_message_length();
    if let Some(ref v) = self.unused_field {
      writer.write_tag(1);
      writer.write_string(&v);
    }
    writer.write_end_marker();
    writer.fill_message_length(pos);
  }

  fn encoded_size(&self) -> usize {
    let mut size = wire::WIRE_MESSAGE_BASE_SIZE;
    if let Some(ref v) = self.unused_field {
      size += wire::tagged_size(wire::string_size(v.len()));
    }
    size
  }
}

impl<'buf> BebopDecode<'buf> for EmptyMessage<'buf> {
  fn decode(reader: &mut BebopReader<'buf>) -> Result<Self, DecodeError> {
    let length = reader.read_message_length()? as usize;
    let end = reader.position() + length;
    let mut msg = Self::default();

    while reader.position() < end {
      let tag = reader.read_tag()?;
      if tag == 0 { break; }
      match tag {
        1 => msg.unused_field = Some(Cow::Borrowed(reader.read_str()?)),
        _ => { reader.skip(end - reader.position())?; }
      }
    }
    Ok(msg)
  }
}

