// Code generated by bebopc-gen-swift. DO NOT EDIT.
// source: /Users/andrew/projects/bebop-vnext/bebop/schemas/bebop/json.bop
// bebopc 2026.0.0
// edition 2026
//
// This file requires the Bebop runtime library.
// https://github.com/6over3/bebop
//
// The Bebop compiler and runtime are licensed under the Apache License,
// Version 2.0. You may obtain a copy of the License at:
// https://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 6OVER3 INSTITUTE
// swiftlint:disable all

// @@bebop_insertion_point(imports)

/// JSON null. Empty struct, zero bytes on wire.
public struct Null: BebopRecord, BebopReflectable {
    public init() {}

    public static func decode(from _: inout BebopReader) throws -> Null {
        // @@bebop_insertion_point(decode_start:Null)
        // @@bebop_insertion_point(decode_end:Null)
        Null()
    }

    public func encode(to _: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Null)
        // @@bebop_insertion_point(encode_end:Null)
    }

    public var encodedSize: Int { 0 }

    public static let bebopReflection = BebopTypeReflection(
        name: "Null",
        fqn: "bebop.Null",
        kind: .struct,
        detail: .struct(
            StructReflection(fields: [
            ])
        )
    )

    // @@bebop_insertion_point(struct_scope:Null)
}

/// Dynamic JSON value.
/// Represents any JSON value: null, boolean, number, string, array, or object.
/// Use for dynamic data when the schema is unknown at compile time.
/// ```bebop
/// message Event {
///   type(1): string;
///   payload(2): bebop.Value;  // arbitrary JSON
/// }
/// ```
public enum Value: BebopRecord, BebopReflectable, Codable {
    case unknown(discriminator: UInt8, data: [UInt8])

    /// JSON null.
    case null(Null)

    /// JSON boolean.
    case bool(Bool)

    /// JSON number. Stored as float64 (IEEE 754 double).
    /// Integers up to 2^53 are exact. Larger integers lose precision.
    case number(Number)

    /// JSON string. UTF-8 encoded.
    case string(String)

    /// JSON array. Ordered list of values.
    case list(List)

    /// JSON object. Unordered string-keyed map.
    case map(Map)

    public static func decode(from reader: inout BebopReader) throws -> Value {
        // @@bebop_insertion_point(decode_start:Value)
        let length = try reader.readMessageLength()
        let end = reader.position + Int(length)
        let disc = try reader.readByte()
        switch disc {
        case 1:
            return try .null(Null.decode(from: &reader))
        case 2:
            return try .bool(Bool.decode(from: &reader))
        case 3:
            return try .number(Number.decode(from: &reader))
        case 4:
            return try .string(String.decode(from: &reader))
        case 5:
            return try .list(List.decode(from: &reader))
        case 6:
            return try .map(Map.decode(from: &reader))
        // @@bebop_insertion_point(decode_switch:Value)
        default:
            let remaining = end - reader.position
            let data = try reader.readBytes(remaining)
            return .unknown(discriminator: disc, data: data)
        }
        // @@bebop_insertion_point(decode_end:Value)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Value)
        let pos = writer.reserveMessageLength()
        switch self {
        case let .null(_v):
            writer.writeByte(1)
            _v.encode(to: &writer)
        case let .bool(_v):
            writer.writeByte(2)
            _v.encode(to: &writer)
        case let .number(_v):
            writer.writeByte(3)
            _v.encode(to: &writer)
        case let .string(_v):
            writer.writeByte(4)
            _v.encode(to: &writer)
        case let .list(_v):
            writer.writeByte(5)
            _v.encode(to: &writer)
        case let .map(_v):
            writer.writeByte(6)
            _v.encode(to: &writer)
        // @@bebop_insertion_point(encode_switch:Value)
        case let .unknown(disc, data):
            writer.writeByte(disc)
            writer.writeBytes(data)
        }
        writer.fillMessageLength(at: pos)
        // @@bebop_insertion_point(encode_end:Value)
    }

    public var encodedSize: Int {
        switch self {
        case let .null(_v):
            4 + 1 + _v.encodedSize
        case let .bool(_v):
            4 + 1 + _v.encodedSize
        case let .number(_v):
            4 + 1 + _v.encodedSize
        case let .string(_v):
            4 + 1 + _v.encodedSize
        case let .list(_v):
            4 + 1 + _v.encodedSize
        case let .map(_v):
            4 + 1 + _v.encodedSize
        case let .unknown(_, data):
            4 + 1 + data.count
        }
    }

    enum CodingKeys: Swift.String, CodingKey { case discriminator, value }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let disc = try container.decode(UInt8.self, forKey: .discriminator)
        switch disc {
        case 1:
            self = try .null(container.decode(Null.self, forKey: .value))
        case 2:
            self = try .bool(container.decode(Bool.self, forKey: .value))
        case 3:
            self = try .number(container.decode(Number.self, forKey: .value))
        case 4:
            self = try .string(container.decode(String.self, forKey: .value))
        case 5:
            self = try .list(container.decode(List.self, forKey: .value))
        case 6:
            self = try .map(container.decode(Map.self, forKey: .value))
        default:
            let data = try container.decode([UInt8].self, forKey: .value)
            self = .unknown(discriminator: disc, data: data)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case let .null(_v):
            try container.encode(UInt8(1), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case let .bool(_v):
            try container.encode(UInt8(2), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case let .number(_v):
            try container.encode(UInt8(3), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case let .string(_v):
            try container.encode(UInt8(4), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case let .list(_v):
            try container.encode(UInt8(5), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case let .map(_v):
            try container.encode(UInt8(6), forKey: .discriminator)
            try container.encode(_v, forKey: .value)
        case let .unknown(disc, data):
            try container.encode(disc, forKey: .discriminator)
            try container.encode(data, forKey: .value)
        }
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Value",
        fqn: "bebop.Value",
        kind: .union,
        detail: .union(
            UnionReflection(branches: [
                (discriminator: 1, name: "null", typeName: "Null"),
                (discriminator: 2, name: "bool", typeName: "Bool"),
                (discriminator: 3, name: "number", typeName: "Number"),
                (discriminator: 4, name: "string", typeName: "String"),
                (discriminator: 5, name: "list", typeName: "List"),
                (discriminator: 6, name: "map", typeName: "Map"),
            ])
        )
    )

    /// JSON boolean.
    public final class Bool: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var value: Swift.Bool?

        public init(value: Swift.Bool? = nil) {
            self.value = value
        }

        public static func == (lhs: Bool, rhs: Bool) -> Swift.Bool {
            lhs.value == rhs.value
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> Bool {
            // @@bebop_insertion_point(decode_start:Bool)
            let length = try reader.readMessageLength()
            let end = reader.position + Int(length)
            var value: Swift.Bool? = nil
            while reader.position < end {
                let tag = try reader.readTag()
                if tag == 0 { break }
                switch tag {
                case 1:
                    value = try reader.readBool()
                default:
                    try reader.skip(end - reader.position)
                }
            }
            // @@bebop_insertion_point(decode_end:Bool)
            return Bool(value: value)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Bool)
            let pos = writer.reserveMessageLength()
            if let _v = value {
                writer.writeTag(1)
                writer.writeBool(_v)
            }
            writer.writeEndMarker()
            writer.fillMessageLength(at: pos)
            // @@bebop_insertion_point(encode_end:Bool)
        }

        public var encodedSize: Int {
            var size = 5
            if value != nil { size += 1 + 1 }
            return size
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Bool",
            fqn: "bebop.Value.Bool",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Swift.Bool"
                    ),
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Bool)
    }

    /// JSON number. Stored as float64 (IEEE 754 double).
    /// Integers up to 2^53 are exact. Larger integers lose precision.
    public final class Number: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var value: Double?

        public init(value: Double? = nil) {
            self.value = value
        }

        public static func == (lhs: Number, rhs: Number) -> Swift.Bool {
            lhs.value == rhs.value
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> Number {
            // @@bebop_insertion_point(decode_start:Number)
            let length = try reader.readMessageLength()
            let end = reader.position + Int(length)
            var value: Double? = nil
            while reader.position < end {
                let tag = try reader.readTag()
                if tag == 0 { break }
                switch tag {
                case 1:
                    value = try reader.readFloat64()
                default:
                    try reader.skip(end - reader.position)
                }
            }
            // @@bebop_insertion_point(decode_end:Number)
            return Number(value: value)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Number)
            let pos = writer.reserveMessageLength()
            if let _v = value {
                writer.writeTag(1)
                writer.writeFloat64(_v)
            }
            writer.writeEndMarker()
            writer.fillMessageLength(at: pos)
            // @@bebop_insertion_point(encode_end:Number)
        }

        public var encodedSize: Int {
            var size = 5
            if value != nil { size += 1 + 8 }
            return size
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Number",
            fqn: "bebop.Value.Number",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Double"
                    ),
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Number)
    }

    /// JSON string. UTF-8 encoded.
    public final class String: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var value: Swift.String?

        public init(value: Swift.String? = nil) {
            self.value = value
        }

        public static func == (lhs: String, rhs: String) -> Swift.Bool {
            lhs.value == rhs.value
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(value)
        }

        public static func decode(from reader: inout BebopReader) throws -> String {
            // @@bebop_insertion_point(decode_start:String)
            let length = try reader.readMessageLength()
            let end = reader.position + Int(length)
            var value: Swift.String? = nil
            while reader.position < end {
                let tag = try reader.readTag()
                if tag == 0 { break }
                switch tag {
                case 1:
                    value = try reader.readString()
                default:
                    try reader.skip(end - reader.position)
                }
            }
            // @@bebop_insertion_point(decode_end:String)
            return String(value: value)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:String)
            let pos = writer.reserveMessageLength()
            if let _v = value {
                writer.writeTag(1)
                writer.writeString(_v)
            }
            writer.writeEndMarker()
            writer.fillMessageLength(at: pos)
            // @@bebop_insertion_point(encode_end:String)
        }

        public var encodedSize: Int {
            var size = 5
            if let _v = value { size += 1 + (4 + _v.utf8.count + 1) }
            return size
        }

        enum CodingKeys: Swift.String, CodingKey {
            case value
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "String",
            fqn: "bebop.Value.String",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "value",
                        index: 1,
                        typeName: "Swift.String"
                    ),
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:String)
    }

    /// JSON array. Ordered list of values.
    public final class List: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var values: [Value]?

        public init(values: [Value]? = nil) {
            self.values = values
        }

        public static func == (lhs: List, rhs: List) -> Swift.Bool {
            lhs.values == rhs.values
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(values)
        }

        public static func decode(from reader: inout BebopReader) throws -> List {
            // @@bebop_insertion_point(decode_start:List)
            let length = try reader.readMessageLength()
            let end = reader.position + Int(length)
            var values: [Value]? = nil
            while reader.position < end {
                let tag = try reader.readTag()
                if tag == 0 { break }
                switch tag {
                case 1:
                    values = try reader.readDynamicArray { _r in try Value.decode(from: &_r) }
                default:
                    try reader.skip(end - reader.position)
                }
            }
            // @@bebop_insertion_point(decode_end:List)
            return List(values: values)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:List)
            let pos = writer.reserveMessageLength()
            if let _v = values {
                writer.writeTag(1)
                writer.writeDynamicArray(_v) { _w, _el in _el.encode(to: &_w) }
            }
            writer.writeEndMarker()
            writer.fillMessageLength(at: pos)
            // @@bebop_insertion_point(encode_end:List)
        }

        public var encodedSize: Int {
            var size = 5
            if let _v = values { size += 1 + (4 + _v.reduce(0) { _acc, _el in _acc + _el.encodedSize }) }
            return size
        }

        enum CodingKeys: Swift.String, CodingKey {
            case values
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "List",
            fqn: "bebop.Value.List",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "values",
                        index: 1,
                        typeName: "[Value]"
                    ),
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:List)
    }

    /// JSON object. Unordered string-keyed map.
    public final class Map: BebopRecord, BebopReflectable, @unchecked Sendable {
        public var fields: [Swift.String: Value]?

        public init(fields: [Swift.String: Value]? = nil) {
            self.fields = fields
        }

        public static func == (lhs: Map, rhs: Map) -> Swift.Bool {
            lhs.fields == rhs.fields
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(fields)
        }

        public static func decode(from reader: inout BebopReader) throws -> Map {
            // @@bebop_insertion_point(decode_start:Map)
            let length = try reader.readMessageLength()
            let end = reader.position + Int(length)
            var fields: [Swift.String: Value]? = nil
            while reader.position < end {
                let tag = try reader.readTag()
                if tag == 0 { break }
                switch tag {
                case 1:
                    fields = try reader.readDynamicMap { _r in try (_r.readString(), Value.decode(from: &_r)) }
                default:
                    try reader.skip(end - reader.position)
                }
            }
            // @@bebop_insertion_point(decode_end:Map)
            return Map(fields: fields)
        }

        public func encode(to writer: inout BebopWriter) {
            // @@bebop_insertion_point(encode_start:Map)
            let pos = writer.reserveMessageLength()
            if let _v = fields {
                writer.writeTag(1)
                writer.writeDynamicMap(_v) { _w, _k, _v in _w.writeString(_k)
                    _v.encode(to: &_w)
                }
            }
            writer.writeEndMarker()
            writer.fillMessageLength(at: pos)
            // @@bebop_insertion_point(encode_end:Map)
        }

        public var encodedSize: Int {
            var size = 5
            if let _v = fields { size += 1 + (4 + _v.reduce(0) { _acc, _kv in let (_k, _v) = _kv; return _acc + (4 + _k.utf8.count + 1) + _v.encodedSize }) }
            return size
        }

        enum CodingKeys: Swift.String, CodingKey {
            case fields
        }

        public static let bebopReflection = BebopTypeReflection(
            name: "Map",
            fqn: "bebop.Value.Map",
            kind: .message,
            detail: .message(
                MessageReflection(fields: [
                    BebopFieldReflection(
                        name: "fields",
                        index: 1,
                        typeName: "[Swift.String: Value]"
                    ),
                ])
            )
        )

        // @@bebop_insertion_point(message_scope:Map)
    }

    // @@bebop_insertion_point(union_scope:Value)
}

/// JSON object. Unordered map of string keys to dynamic values.
/// Equivalent to `Value.Map` but as a standalone type. Use when you know
/// the value is an object (not null, bool, number, string, or list).
/// ```bebop
/// message Request {
///   headers(1): bebop.Object;  // {"Content-Type": "application/json", ...}
/// }
/// ```
public final class Object: BebopRecord, BebopReflectable, @unchecked Sendable {
    public var fields: [String: Value]?

    public init(fields: [String: Value]? = nil) {
        self.fields = fields
    }

    public static func == (lhs: Object, rhs: Object) -> Bool {
        lhs.fields == rhs.fields
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(fields)
    }

    public static func decode(from reader: inout BebopReader) throws -> Object {
        // @@bebop_insertion_point(decode_start:Object)
        let length = try reader.readMessageLength()
        let end = reader.position + Int(length)
        var fields: [String: Value]? = nil
        while reader.position < end {
            let tag = try reader.readTag()
            if tag == 0 { break }
            switch tag {
            case 1:
                fields = try reader.readDynamicMap { _r in try (_r.readString(), Value.decode(from: &_r)) }
            default:
                try reader.skip(end - reader.position)
            }
        }
        // @@bebop_insertion_point(decode_end:Object)
        return Object(fields: fields)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:Object)
        let pos = writer.reserveMessageLength()
        if let _v = fields {
            writer.writeTag(1)
            writer.writeDynamicMap(_v) { _w, _k, _v in _w.writeString(_k)
                _v.encode(to: &_w)
            }
        }
        writer.writeEndMarker()
        writer.fillMessageLength(at: pos)
        // @@bebop_insertion_point(encode_end:Object)
    }

    public var encodedSize: Int {
        var size = 5
        if let _v = fields { size += 1 + (4 + _v.reduce(0) { _acc, _kv in let (_k, _v) = _kv; return _acc + (4 + _k.utf8.count + 1) + _v.encodedSize }) }
        return size
    }

    enum CodingKeys: String, CodingKey {
        case fields
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "Object",
        fqn: "bebop.Object",
        kind: .message,
        detail: .message(
            MessageReflection(fields: [
                BebopFieldReflection(
                    name: "fields",
                    index: 1,
                    typeName: "[String: Value]"
                ),
            ])
        )
    )

    // @@bebop_insertion_point(message_scope:Object)
}

/// JSON array. Ordered list of dynamic values.
/// Equivalent to `Value.List` but as a standalone type. Use when you know
/// the value is an array.
public final class List: BebopRecord, BebopReflectable, @unchecked Sendable {
    public var values: [Value]?

    public init(values: [Value]? = nil) {
        self.values = values
    }

    public static func == (lhs: List, rhs: List) -> Bool {
        lhs.values == rhs.values
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(values)
    }

    public static func decode(from reader: inout BebopReader) throws -> List {
        // @@bebop_insertion_point(decode_start:List)
        let length = try reader.readMessageLength()
        let end = reader.position + Int(length)
        var values: [Value]? = nil
        while reader.position < end {
            let tag = try reader.readTag()
            if tag == 0 { break }
            switch tag {
            case 1:
                values = try reader.readDynamicArray { _r in try Value.decode(from: &_r) }
            default:
                try reader.skip(end - reader.position)
            }
        }
        // @@bebop_insertion_point(decode_end:List)
        return List(values: values)
    }

    public func encode(to writer: inout BebopWriter) {
        // @@bebop_insertion_point(encode_start:List)
        let pos = writer.reserveMessageLength()
        if let _v = values {
            writer.writeTag(1)
            writer.writeDynamicArray(_v) { _w, _el in _el.encode(to: &_w) }
        }
        writer.writeEndMarker()
        writer.fillMessageLength(at: pos)
        // @@bebop_insertion_point(encode_end:List)
    }

    public var encodedSize: Int {
        var size = 5
        if let _v = values { size += 1 + (4 + _v.reduce(0) { _acc, _el in _acc + _el.encodedSize }) }
        return size
    }

    enum CodingKeys: String, CodingKey {
        case values
    }

    public static let bebopReflection = BebopTypeReflection(
        name: "List",
        fqn: "bebop.List",
        kind: .message,
        detail: .message(
            MessageReflection(fields: [
                BebopFieldReflection(
                    name: "values",
                    index: 1,
                    typeName: "[Value]"
                ),
            ])
        )
    )

    // @@bebop_insertion_point(message_scope:List)
}

// @@bebop_insertion_point(eof)
