name: CI

on:
  push:
    branches: [main, lsp]
  pull_request:
    branches: [main]

jobs:
  linux-x64:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      arch: x64

  linux-arm64:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-24.04-arm
      arch: arm64

  macos-arm64:
    uses: ./.github/workflows/build.yml
    with:
      os: macos-latest
      arch: arm64

  macos-x64:
    uses: ./.github/workflows/build.yml
    with:
      os: macos-13
      arch: x64

  windows-x64:
    uses: ./.github/workflows/build.yml
    with:
      os: windows-latest
      arch: x64

  codegen-c:
    needs: [linux-x64]
    uses: ./.github/workflows/codegen.yml
    with:
      artifact: bebopc-ubuntu-latest-x64
      generator: c
